// src/react/components/Tooltip/TooltipRoot.tsx
import {useSyncExternalStore} from 'react'

import {
	getTooltipSnapshot,
	setTooltipOpen,
	subscribeTooltip,
	TOOLTIP_ANCHOR_NAME,
} from '../../../core'
import {classNames} from '../../classNames'
import {Popover} from '../Popover'
import styles from './TooltipRoot.module.styl'

export function TooltipRoot() {
	const tooltip = useSyncExternalStore(
		subscribeTooltip,
		getTooltipSnapshot,
		getTooltipSnapshot
	)

	return (
		<Popover
			reference={tooltip.reference}
			open={tooltip.open}
			anchorName={TOOLTIP_ANCHOR_NAME}
			placement="top"
			lightDismiss={false}
			arrow
			teleport=".TqViewport"
			onChangeOpen={open => {
				if (!open) setTooltipOpen(false)
			}}
		>
			{tooltip.title || tooltip.description ? (
				<div className={classNames(styles.content, styles.structured)}>
					{tooltip.title && <div className={styles.title}>{tooltip.title}</div>}
					{tooltip.description && (
						<div className={styles.description}>{tooltip.description}</div>
					)}
				</div>
			) : tooltip.html ? (
				<div
					className={classNames(styles.content, styles.html)}
					dangerouslySetInnerHTML={{__html: tooltip.content}}
				/>
			) : (
				<div className={classNames(styles.content, styles.plain)}>
					{tooltip.content}
				</div>
			)}
		</Popover>
	)
}

// packages/vue/src/Tooltip/TooltipRoot.vue
<script setup lang="ts">
import {computed} from 'vue'

import {Popover} from '../Popover'
import {
	setTooltipOpen,
	TOOLTIP_ANCHOR_NAME,
	tooltipReference,
	tooltipState,
} from './tooltip'

const reference = computed(() => tooltipReference.value)

// Sync back the native popover's own close (Esc / programmatic), so the shared
// state never gets stuck open.
function onUpdateOpen(open: boolean) {
	if (!open) setTooltipOpen(false)
}
</script>

<template>
	<Popover
		:reference="reference"
		:open="tooltipState.open"
		:anchor-name="TOOLTIP_ANCHOR_NAME"
		placement="top"
		:light-dismiss="false"
		arrow
		teleport=".TqViewport"
		@update:open="onUpdateOpen"
	>
		<!-- Structured: bold title + muted description (replaces "Title — sub"). -->
		<div
			v-if="tooltipState.title || tooltipState.description"
			class="TqTooltipContent structured"
			data-tq-component="tooltip-content"
			data-tq-part="tooltip-content"
			data-tq-variant="structured"
		>
			<div v-if="tooltipState.title" class="title" data-tq-part="title">
				{{ tooltipState.title }}
			</div>
			<div v-if="tooltipState.description" class="description" data-tq-part="description">
				{{ tooltipState.description }}
			</div>
		</div>
		<!-- eslint-disable-next-line vue/no-v-html -->
		<div
			v-else-if="tooltipState.html"
			class="TqTooltipContent html"
			data-tq-component="tooltip-content"
			data-tq-part="tooltip-content"
			data-tq-variant="html"
			v-html="tooltipState.content"
		/>
		<div
			v-else
			class="TqTooltipContent plain"
			data-tq-component="tooltip-content"
			data-tq-part="tooltip-content"
			data-tq-variant="plain"
		>
			{{ tooltipState.content }}
		</div>
	</Popover>
</template>
