// packages/vue/src/InputShuffle/InputShuffle.vue
<script lang="ts" setup generic="T">
import {random} from 'lodash-es'
import {ref} from 'vue'

import {Icon} from '../Icon'
import {SvgIcon} from '../SvgIcon'
import type {InputShuffleProps} from './types'

const props = defineProps<InputShuffleProps<T>>()

const model = defineModel<T>({required: true})

const iconRot = ref(0)
// The die face is just flair now (values may be non-numeric), so roll it.
const iconNum = ref(3)

function shuffle() {
	iconRot.value += 90
	iconNum.value = random(1, 6)
	model.value = props.generate(model.value)
}
</script>

<template>
	<button
		class="TqInputShuffle"
		type="button"
		:disabled="disabled"
		:aria-invalid="invalid || undefined"
		data-tq-component="input-shuffle"
		data-tq-part="root"
		@click="shuffle"
	>
		<Icon
			v-if="icon"
			class="icon"
			:icon="icon"
			data-tq-part="icon"
			:style="{transform: `rotate(${iconRot}deg)`}"
		/>
		<SvgIcon
			v-else
			mode="block"
			class="icon"
			data-tq-part="icon"
			:style="{transform: `rotate(${iconRot}deg)`}"
		>
			<circle v-show="iconNum === 1" cx="16" cy="16" r="1" />
			<g v-show="iconNum === 2">
				<circle cx="11" cy="21" r="1" />
				<circle cx="21" cy="11" r="1" />
			</g>
			<g v-show="iconNum === 3">
				<circle cx="16" cy="16" r="1" />
				<circle cx="10" cy="22" r="1" />
				<circle cx="22" cy="10" r="1" />
			</g>
			<g v-show="iconNum === 4">
				<circle cx="10" cy="22" r="1" />
				<circle cx="22" cy="10" r="1" />
				<circle cx="10" cy="10" r="1" />
				<circle cx="22" cy="22" r="1" />
			</g>
			<g v-show="iconNum === 5">
				<circle cx="16" cy="16" r="1" />
				<circle cx="10" cy="22" r="1" />
				<circle cx="22" cy="10" r="1" />
				<circle cx="10" cy="10" r="1" />
				<circle cx="22" cy="22" r="1" />
			</g>
			<g v-show="iconNum === 6">
				<circle cx="10" cy="10" r="1" />
				<circle cx="10" cy="16" r="1" />
				<circle cx="10" cy="22" r="1" />
				<circle cx="22" cy="10" r="1" />
				<circle cx="22" cy="16" r="1" />
				<circle cx="22" cy="22" r="1" />
			</g>
			<path
				d="M24,29H8c-2.8,0-5-2.2-5-5V8c0-2.8,2.2-5,5-5h16c2.8,0,5,2.2,5,5v16C29,26.8,26.8,29,24,29z"
			/>
		</SvgIcon>
	</button>
</template>

// src/react/components/InputShuffle/InputShuffle.tsx
import {type ButtonHTMLAttributes, useState} from 'react'

import {classNames} from '../../classNames'
import {Icon} from '../Icon'
import {SvgIcon} from '../SvgIcon'
import styles from './InputShuffle.module.styl'

export interface InputShuffleProps<T>
	extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onChange' | 'value'> {
	value: T
	onChange?: (value: T) => void
	generate: (previous: T) => T
	icon?: string
}

export function InputShuffle<T>({
	value,
	onChange,
	generate,
	icon,
	className,
	onClick,
	...props
}: InputShuffleProps<T>) {
	const [rotation, setRotation] = useState(0)
	const [face, setFace] = useState(3)

	return (
		<button
			{...props}
			className={classNames(styles.tqInputShuffle, className)}
			onClick={event => {
				onClick?.(event)
				if (event.defaultPrevented) return
				setRotation(current => current + 90)
				setFace(Math.floor(Math.random() * 6) + 1)
				onChange?.(generate(value))
			}}
		>
			{icon ? (
				<Icon
					className={styles.icon}
					icon={icon}
					style={{transform: `rotate(${rotation}deg)`}}
				/>
			) : (
				<Dice face={face} rotation={rotation} />
			)}
		</button>
	)
}

function Dice({face, rotation}: {face: number; rotation: number}) {
	const dots: Record<number, [number, number][]> = {
		1: [[16, 16]],
		2: [
			[11, 21],
			[21, 11],
		],
		3: [
			[16, 16],
			[10, 22],
			[22, 10],
		],
		4: [
			[10, 22],
			[22, 10],
			[10, 10],
			[22, 22],
		],
		5: [
			[16, 16],
			[10, 22],
			[22, 10],
			[10, 10],
			[22, 22],
		],
		6: [
			[10, 10],
			[10, 16],
			[10, 22],
			[22, 10],
			[22, 16],
			[22, 22],
		],
	}

	return (
		<SvgIcon
			mode="block"
			className={styles.icon}
			style={{transform: `rotate(${rotation}deg)`}}
		>
			{dots[face].map(([cx, cy]) => (
				<circle key={`${cx}-${cy}`} cx={cx} cy={cy} r="1" />
			))}
			<path d="M24,29H8c-2.8,0-5-2.2-5-5V8c0-2.8,2.2-5,5-5h16c2.8,0,5,2.2,5,5v16C29,26.8,26.8,29,24,29z" />
		</SvgIcon>
	)
}
