// packages/react/src/components/InputNumber/InputNumberScales.tsx
import {useMemo, useRef} from 'react'

import {useElementBounding} from '../../hooks'

export interface InputNumberScalesProps {
	min?: number
	max?: number
	step?: number
}

export function InputNumberScales({min, max, step}: InputNumberScalesProps) {
	const element = useRef<HTMLDivElement>(null)
	const {width} = useElementBounding(element)
	const gap =
		min === undefined || max === undefined || step === undefined || width === 0
			? 0
			: (step / (max - min)) * width
	const style = useMemo(
		() => (gap >= 10 ? {backgroundSize: `${gap}px 100%`} : undefined),
		[gap]
	)

	return (
		<div
			ref={element}
			data-tq-component="input-number-scales"
			data-tq-part="root"
			style={style}
		/>
	)
}

// packages/vue/src/InputNumber/InputNumberScales.vue
<script lang="ts" setup>
import {useElementSize} from '@vueuse/core'
import {computed, useTemplateRef} from 'vue'

interface Props {
	min?: number
	max?: number
	step?: number
}

const props = defineProps<Props>()

const $el = useTemplateRef('$el')

const {width} = useElementSize($el)

const scaleGap = computed(() => {
	if (
		props.max === undefined ||
		props.min === undefined ||
		props.step === undefined ||
		width.value === 0
	) {
		return 0
	}

	const gap = (props.step / (props.max - props.min)) * width.value

	return gap < 10 ? 0 : gap
})

const style = computed(() => {
	if (scaleGap.value === 0) return {}

	return {
		backgroundSize: `${scaleGap.value}px 100%`,
	}
})
</script>

<template>
	<div
		ref="$el"
		data-tq-component="input-number-scales"
		data-tq-part="root"
		:style="style"
	/>
</template>
