// packages/vue/src/PaneFloating/PaneFloating.vue
<script lang="ts" setup>
import {resizeFloatingPane} from '@tweeq/core'
import {useCssVar, useWindowSize} from '@vueuse/core'
import {computed, type Ref, useTemplateRef, watch} from 'vue'

import {Icon} from '../Icon'
import {useAppConfigStore} from '../stores/appConfig'
import {useDrag} from '../use/useDrag'
import type {PaneFloatingProps, Position} from './types'

const props = withDefaults(defineProps<PaneFloatingProps>(), {
	position: () => {
		return {
			anchor: 'right-top',
			width: 400,
			height: 400,
		}
	},
})

const emit = defineEmits<{
	'update:position': [Position]
}>()

const appConfig = useAppConfigStore()

const position = appConfig.ref(`${props.name}.position`, props.position)

const windowSize = useWindowSize()

const style = computed(() => {
	const w = 'width' in position.value ? position.value.width : null
	const h = 'height' in position.value ? position.value.height : null
	return {
		width: typeof w === 'number' ? w + 'px' : '',
		height: typeof h === 'number' ? h + 'px' : '',
	}
})

const $root = useTemplateRef('$root')
const $top = useTemplateRef('$top')
const $right = useTemplateRef('$right')
const $left = useTemplateRef('$left')
const $bottom = useTemplateRef('$bottom')

const titlebarHeight = useCssVar('--titlebar-area-height')
const maxHeight = computed(
	() =>
		windowSize.height.value - Number.parseFloat(titlebarHeight.value || '0')
)

watch([windowSize.width, maxHeight], ([width, height]) => {
	let next = position.value
	if ('width' in next && typeof next.width === 'number' && next.width > width) {
		next = {...next, width}
	}
	if (
		'height' in next &&
		typeof next.height === 'number' &&
		next.height > height
	) {
		next = {...next, height}
	}
	if (next !== position.value) position.value = next
})

function installResize(
	target: Ref<HTMLElement | null>,
	axis: 'width' | 'height',
	edge: 'near' | 'far'
) {
	let sizeAtDragStart = 0
	useDrag(target, {
		dragDelaySeconds: 0,
		onDragStart() {
			const bounds = $root.value?.getBoundingClientRect()
			sizeAtDragStart = axis === 'width' ? bounds?.width ?? 0 : bounds?.height ?? 0
		},
		onDrag({xy, initial}) {
			const movement = axis === 'width' ? xy[0] - initial[0] : xy[1] - initial[1]
			const current = Math.round(
				sizeAtDragStart + movement * (edge === 'near' ? -1 : 1)
			)
			position.value = resizeFloatingPane({
				position: position.value,
				axis,
				edge,
				current,
				viewport: axis === 'width' ? windowSize.width.value : maxHeight.value,
			})
		},
	})
}

installResize($left, 'width', 'near')
installResize($right, 'width', 'far')
installResize($top, 'height', 'near')
installResize($bottom, 'height', 'far')

watch(position, position => emit('update:position', position))
</script>

<template>
	<div
		ref="$root"
		class="TqPaneFloating"
		:style="style"
		data-tq-component="pane-floating"
		:data-tq-anchor="position.anchor"
		:data-tq-anchor-maximized="position.anchor === 'maximized' ? '' : undefined"
		:data-tq-anchor-top="position.anchor.includes('top') ? '' : undefined"
		:data-tq-anchor-right="position.anchor.includes('right') ? '' : undefined"
		:data-tq-anchor-bottom="position.anchor.includes('bottom') ? '' : undefined"
		:data-tq-anchor-left="position.anchor.includes('left') ? '' : undefined"
		:data-tq-width-minimized="
			'width' in position && position.width === 'minimized' ? '' : undefined
		"
		:data-tq-height-minimized="
			'height' in position && position.height === 'minimized' ? '' : undefined
		"
		data-tq-part="root"
	>
		<div ref="$top" data-tq-resize-edge="top" data-tq-part="top" />
		<div ref="$right" data-tq-resize-edge="right" data-tq-part="right" />
		<div ref="$left" data-tq-resize-edge="left" data-tq-part="left" />
		<div ref="$bottom" data-tq-resize-edge="bottom" data-tq-part="bottom" />
		<Icon v-if="icon" data-tq-part="minimized-title" :icon="icon" />
		<div data-tq-part="wrapper">
			<div data-tq-part="content">
				<slot />
			</div>
		</div>
	</div>
</template>

// packages/react/src/components/PaneFloating/PaneFloating.tsx
import {type FloatingPanePosition, resizeFloatingPane} from '@tweeq/core'
import {appConfigStore, type DragState} from '@tweeq/dom'
import {
	type CSSProperties,
	type HTMLAttributes,
	useEffect,
	useMemo,
	useRef,
} from 'react'

import {useConfigRef, useDrag, useWindowSize} from '../../hooks'
import {Icon} from '../Icon'

const DEFAULT_POSITION: FloatingPanePosition = {
	anchor: 'right-top',
	width: 400,
	height: 400,
}

export type PaneFloatingPosition = FloatingPanePosition

export interface PaneFloatingProps extends HTMLAttributes<HTMLDivElement> {
	name: string
	icon?: string
	position?: FloatingPanePosition
	onChangePosition?: (position: FloatingPanePosition) => void
}

export function PaneFloating({
	name,
	icon,
	position: defaultPosition = DEFAULT_POSITION,
	onChangePosition,
	children,
	className,
	style,
	...props
}: PaneFloatingProps) {
	const root = useRef<HTMLDivElement>(null)
	const top = useRef<HTMLDivElement>(null)
	const right = useRef<HTMLDivElement>(null)
	const bottom = useRef<HTMLDivElement>(null)
	const left = useRef<HTMLDivElement>(null)
	const windowSize = useWindowSize()
	const entry = useMemo(
		() => appConfigStore.getState().ref(`${name}.position`, defaultPosition),
		[defaultPosition, name]
	)
	const [position, setStoredPosition] = useConfigRef(entry)
	const positionRef = useRef(position)
	positionRef.current = position
	const callbacks = useRef({onChangePosition})
	callbacks.current = {onChangePosition}
	const startSize = useRef(0)
	const setPosition = (next: FloatingPanePosition) => {
		positionRef.current = next
		setStoredPosition(next)
		callbacks.current.onChangePosition?.(next)
	}
	const makeDragOptions = (axis: 'width' | 'height', edge: 'near' | 'far') => ({
		dragDelaySeconds: 0,
		onDragStart: () => {
			const rect = root.current?.getBoundingClientRect()
			startSize.current =
				axis === 'width' ? rect?.width ?? 0 : rect?.height ?? 0
		},
		onDrag: (drag: DragState) => {
			const delta =
				axis === 'width'
					? drag.xy[0] - drag.initial[0]
					: drag.xy[1] - drag.initial[1]
			const current = Math.round(
				startSize.current + delta * (edge === 'near' ? -1 : 1)
			)
			const titlebarHeight =
				Number.parseFloat(
					getComputedStyle(document.documentElement).getPropertyValue(
						'--titlebar-area-height'
					)
				) || 0
			setPosition(
				resizeFloatingPane({
					position: positionRef.current,
					axis,
					edge,
					current,
					viewport:
						axis === 'width'
							? window.innerWidth
							: window.innerHeight - titlebarHeight,
				})
			)
		},
	})
	useDrag(
		left,
		useMemo(() => makeDragOptions('width', 'near'), [])
	)
	useDrag(
		right,
		useMemo(() => makeDragOptions('width', 'far'), [])
	)
	useDrag(
		top,
		useMemo(() => makeDragOptions('height', 'near'), [])
	)
	useDrag(
		bottom,
		useMemo(() => makeDragOptions('height', 'far'), [])
	)

	useEffect(() => {
		let next = positionRef.current
		const titlebarHeight =
			Number.parseFloat(
				getComputedStyle(document.documentElement).getPropertyValue(
					'--titlebar-area-height'
				)
			) || 0
		const maxHeight = windowSize.height - titlebarHeight
		if (
			'width' in next &&
			typeof next.width === 'number' &&
			next.width > windowSize.width
		) {
			next = {...next, width: windowSize.width}
		}
		if (
			'height' in next &&
			typeof next.height === 'number' &&
			next.height > maxHeight
		) {
			next = {...next, height: maxHeight}
		}
		if (next !== positionRef.current) setPosition(next)
	}, [windowSize.height, windowSize.width])

	const hasWidth = 'width' in position
	const hasHeight = 'height' in position
	const rootStyle = {
		...style,
		width:
			hasWidth && typeof position.width === 'number'
				? `${position.width}px`
				: undefined,
		height:
			hasHeight && typeof position.height === 'number'
				? `${position.height}px`
				: undefined,
	} as CSSProperties
	const anchor = position.anchor

	return (
		<div
			{...props}
			ref={root}
			className={className}
			style={rootStyle}
			data-tq-component="pane-floating"
			data-tq-anchor={anchor}
			data-tq-anchor-maximized={anchor === 'maximized' ? '' : undefined}
			data-tq-anchor-top={anchor.includes('top') ? '' : undefined}
			data-tq-anchor-right={anchor.includes('right') ? '' : undefined}
			data-tq-anchor-bottom={anchor.includes('bottom') ? '' : undefined}
			data-tq-anchor-left={anchor.includes('left') ? '' : undefined}
			data-tq-width-minimized={
				hasWidth && position.width === 'minimized' ? '' : undefined
			}
			data-tq-height-minimized={
				hasHeight && position.height === 'minimized' ? '' : undefined
			}
			data-tq-part="root"
		>
			<div ref={top} data-tq-resize-edge="top" data-tq-part="top" />
			<div ref={right} data-tq-resize-edge="right" data-tq-part="right" />
			<div ref={bottom} data-tq-resize-edge="bottom" data-tq-part="bottom" />
			<div ref={left} data-tq-resize-edge="left" data-tq-part="left" />
			{icon && <Icon data-tq-part="minimized-title" icon={icon} />}
			<div data-tq-part="wrapper">
				<div data-tq-part="content">{children}</div>
			</div>
		</div>
	)
}
