// packages/react/src/components/InputTranslate/InputTranslate.tsx
import {
	decomposeVec2,
	getTranslateOverlayGeometry,
	type InputBoxProps,
	type InputEvents,
	precisionOf,
} from '@tweeq/core'
import type {DragState} from '@tweeq/dom'
import {type vec2} from 'linearly'
import {
	type ButtonHTMLAttributes,
	useEffect,
	useMemo,
	useRef,
	useState,
} from 'react'

import {useDrag, useKeys} from '../../hooks'
import {Icon} from '../Icon'
import {Tooltip} from '../Tooltip'
import styles from './InputTranslate.module.styl'

const TRANSLATE_KEYS = ['Shift', 'Alt', 'x', 'y'] as const

export interface InputTranslateProps
	extends InputBoxProps,
		InputEvents,
		Omit<
			ButtonHTMLAttributes<HTMLButtonElement>,
			'onBlur' | 'onChange' | 'onFocus' | 'value'
		> {
	value: vec2
	onChange?: (value: vec2) => void
	min?: vec2 | number
	max?: vec2 | number
	step?: vec2 | number
	showOverlayLabel?: boolean
}

export function InputTranslate({
	value,
	onChange,
	min: minProp,
	max: maxProp,
	showOverlayLabel = true,
	disabled,
	invalid,
	inlinePosition,
	blockPosition,
	onFocus,
	onBlur,
	onConfirm,
	...props
}: InputTranslateProps) {
	const button = useRef<HTMLButtonElement>(null)
	const keys = useKeys(TRANSLATE_KEYS)
	const keysRef = useRef(keys)
	keysRef.current = keys
	const valueRef = useRef(value)
	valueRef.current = value
	const callbacksRef = useRef({onChange, onFocus, onBlur, onConfirm, disabled})
	callbacksRef.current = {onChange, onFocus, onBlur, onConfirm, disabled}
	const min = decomposeVec2(minProp)
	const max = decomposeVec2(maxProp)
	const boundsRef = useRef({min, max})
	boundsRef.current = {min, max}
	const targetGridScale = keys.Shift ? 0.5 : keys.Alt ? 4 : 2
	const [gridScale, setGridScale] = useState(1)

	useEffect(() => {
		let frame: number
		const tick = () => {
			setGridScale(current => {
				const next = current + (targetGridScale - current) * 0.4
				if (Math.abs(next - targetGridScale) < 0.001) return targetGridScale
				frame = requestAnimationFrame(tick)
				return next
			})
		}
		frame = requestAnimationFrame(tick)
		return () => cancelAnimationFrame(frame)
	}, [targetGridScale])

	const dragOptions = useMemo(
		() => ({
			lockPointer: true,
			disabled: () => Boolean(callbacksRef.current.disabled),
			dragDelaySeconds: 0,
			onDragStart() {
				callbacksRef.current.onFocus?.()
			},
			onDrag({delta}: DragState) {
				const speed = keysRef.current.Shift ? 5 : keysRef.current.Alt ? 0.1 : 1
				const modelDelta: [number, number] = [
					delta[0] * speed,
					delta[1] * speed,
				]
				if (keysRef.current.x) modelDelta[1] = 0
				if (keysRef.current.y) modelDelta[0] = 0
				const currentBounds = boundsRef.current
				callbacksRef.current.onChange?.([
					Math.max(
						currentBounds.min?.[0] ?? -Infinity,
						Math.min(
							currentBounds.max?.[0] ?? Infinity,
							valueRef.current[0] + modelDelta[0]
						)
					),
					Math.max(
						currentBounds.min?.[1] ?? -Infinity,
						Math.min(
							currentBounds.max?.[1] ?? Infinity,
							valueRef.current[1] + modelDelta[1]
						)
					),
				])
			},
			onDragEnd() {
				callbacksRef.current.onConfirm?.()
				callbacksRef.current.onBlur?.()
			},
		}),
		[]
	)
	const drag = useDrag(button, dragOptions)
	const geometry = getTranslateOverlayGeometry({
		value,
		min,
		max,
		scale: gridScale,
	})
	const precision = precisionOf(keys.Shift ? 5 : keys.Alt ? 0.1 : 1)

	return (
		<button
			{...props}
			ref={button}
			className={styles.tqInputTranslate}
			type="button"
			disabled={disabled}
			aria-invalid={invalid || undefined}
			inline-position={inlinePosition}
			block-position={blockPosition}
			data-tq-part="root"
		>
			<Icon
				className={styles.gridIcon}
				icon="mingcute:dot-grid-fill"
				data-tq-part="icon"
			/>
			{drag.dragging && (
				<div className={styles.overlay} data-tq-part="overlay">
					<div
						className={styles.overlayGrid}
						style={geometry.grid}
						data-tq-part="overlay-grid"
					>
						{keys.x && <div className={`${styles.axis} ${styles.x}`} />}
						{keys.y && <div className={`${styles.axis} ${styles.y}`} />}
						<div
							className={styles.zero}
							style={geometry.zero}
							data-tq-part="zero"
						/>
					</div>
					{showOverlayLabel && (
						<Tooltip className={styles.overlayLabel}>
							<label>X</label> {value[0].toFixed(precision)} <label>Y</label>{' '}
							{value[1].toFixed(precision)}
						</Tooltip>
					)}
				</div>
			)}
		</button>
	)
}

// packages/vue/src/InputTranslate/InputTranslate.vue
<script setup lang="ts">
import {
	decomposeVec2,
	getTranslateOverlayGeometry,
	precisionOf,
} from '@tweeq/core'
import {useMagicKeys, useRafFn} from '@vueuse/core'
import {scalar, vec2} from 'linearly'
import {computed, ref, useTemplateRef} from 'vue'

import {Icon} from '../Icon'
import {InputPositionProps} from '../InputPosition'
import {Tooltip} from '../Tooltip'
import {InputEmits} from '../types'
import {useDrag} from '../use/useDrag'

const model = defineModel<vec2>({required: true})

const props = withDefaults(
	defineProps<InputPositionProps & {showOverlayLabel?: boolean}>(),
	{
		showOverlayLabel: true,
	}
)
const emit = defineEmits<InputEmits>()

const $button = useTemplateRef('$button')

const {shift, alt, x, y} = useMagicKeys()

const min = computed(() => decomposeVec2(props.min))
const max = computed(() => decomposeVec2(props.max))

const speed = computed(() => {
	if (shift.value) return 5
	if (alt.value) return 0.1
	return 1
})

const gridScale = computed(() => {
	if (shift.value) return 0.5
	if (alt.value) return 4
	return 2
})

const gridScaleAnimated = ref(1)
useRafFn(() => {
	gridScaleAnimated.value = scalar.lerp(
		gridScaleAnimated.value,
		gridScale.value,
		0.4
	)
})

const precision = computed(() => {
	return precisionOf(speed.value)
})

const overlayLabelValues = computed(() => {
	const xd = model.value[0].toFixed(precision.value)
	const yd = model.value[1].toFixed(precision.value)

	return [xd, yd]
})

const {dragging: tweaking} = useDrag($button, {
	disabled: computed(() => props.disabled),
	lockPointer: true,
	dragDelaySeconds: 0,
	onDragStart() {
		emit('focus')
	},
	onDrag({delta}) {
		const modelDelta = vec2.scale(delta, speed.value) as vec2.Mutable

		if (x.value) {
			modelDelta[1] = 0
		}

		if (y.value) {
			modelDelta[0] = 0
		}

		model.value = vec2.clamp(
			vec2.add(model.value, modelDelta),
			min.value ?? [-Infinity, -Infinity],
			max.value ?? [Infinity, Infinity]
		)
	},
	onDragEnd() {
		emit('confirm')
		emit('blur')
	},
})

const geometry = computed(() =>
	getTranslateOverlayGeometry({
		value: model.value,
		min: min.value,
		max: max.value,
		scale: gridScaleAnimated.value,
	})
)
</script>

<template>
	<button
		ref="$button"
		class="TqInputTranslate"
		type="button"
		:disabled="props.disabled"
		:aria-invalid="props.invalid || undefined"
		:inline-position="props.inlinePosition"
		:block-position="props.blockPosition"
		data-tq-component="input-translate"
		data-tq-part="root"
	>
		<Icon
			class="grid-icon"
			icon="mingcute:dot-grid-fill"
			data-tq-part="icon"
		/>
		<Transition
			enter-from-class="tq-input-translate-overlay-hidden"
			leave-to-class="tq-input-translate-overlay-hidden"
		>
			<div v-if="tweaking" class="overlay" data-tq-part="overlay">
				<div
					class="overlay-grid"
					:style="geometry.grid"
					data-tq-part="overlay-grid"
				>
					<div v-if="x" data-tq-part="axis" data-tq-axis="x" />
					<div v-if="y" data-tq-part="axis" data-tq-axis="y" />
					<div
						class="zero"
						:style="geometry.zero"
						data-tq-part="zero"
					/>
				</div>
				<Tooltip
					v-if="showOverlayLabel"
					data-tq-part="overlay-label"
				>
					<label>X</label>
					{{ overlayLabelValues[0] }}
					<label>Y</label>
					{{ overlayLabelValues[1] }}
				</Tooltip>
			</div>
		</Transition>
	</button>
</template>
