// packages/react/src/components/TweeqProvider/TweeqProvider.tsx
import {Fragment, type PropsWithChildren, useEffect} from 'react'

import {type TweeqOptions} from '../../initTweeq'
import {TweeqRuntimeProvider, useOwnedTweeqRuntime} from '../../runtime'
import {CommandPalette} from '../CommandPalette'
import {InputColorProvider} from '../InputColor/InputColorContext'
import {MultiSelectPopup} from '../MultiSelectPopup'
import {PaneModalComplex} from '../PaneModalComplex'
import {PaneModalTabs} from '../PaneModalTabs'
import {TooltipRoot} from '../Tooltip'

export interface TweeqProviderProps extends PropsWithChildren, TweeqOptions {
	appId: string
}

export function TweeqProvider({
	appId,
	colorMode,
	accentColor,
	backgroundColor,
	grayColor,
	colorPresets,
	children,
}: TweeqProviderProps) {
	const runtime = useOwnedTweeqRuntime(appId, {
		colorMode,
		accentColor,
		backgroundColor,
		grayColor,
	})
	useEffect(() => {
		runtime.configure(appId, {
			colorMode,
			accentColor,
			backgroundColor,
			grayColor,
		})
	}, [accentColor, appId, backgroundColor, colorMode, grayColor, runtime])

	return (
		<TweeqRuntimeProvider runtime={runtime} bind disposeOnUnmount>
			<InputColorProvider presets={colorPresets}>
				<Fragment>
					{children}
					<CommandPalette />
					<MultiSelectPopup />
					<PaneModalComplex />
					<PaneModalTabs />
					<TooltipRoot />
				</Fragment>
			</InputColorProvider>
		</TweeqRuntimeProvider>
	)
}

// packages/vue/src/TweeqProvider/TweeqProvider.vue
<script lang="ts" setup>
import {createTweeqRuntime} from '@tweeq/dom'
import {onBeforeUnmount, onMounted, watch} from 'vue'

import {CommandPalette} from '../CommandPalette'
import {useInputColor} from '../InputColor/useInputColor'
import {MultiSelectPopup} from '../MultiSelectPopup'
import {PaneModalComplex} from '../PaneModalComplex'
import {PaneModalTabs} from '../PaneModalTabs'
import {TooltipRoot} from '../Tooltip'
import {provideTweeqRuntime} from '../runtime'
import type {TweeqProviderProps} from './types'

const props = withDefaults(defineProps<TweeqProviderProps>(), {appId: 'app'})
const runtime = createTweeqRuntime({
	appId: props.appId,
	colorMode: props.colorMode,
	accentColor: props.accentColor,
	backgroundColor: props.backgroundColor,
	grayColor: props.grayColor,
})
provideTweeqRuntime(runtime)
useInputColor(props.colorPresets)
watch(
	() => [
		props.appId,
		props.colorMode,
		props.accentColor,
		props.backgroundColor,
		props.grayColor,
	],
	() => runtime.configure(props.appId, props)
)
let unbind: (() => void) | undefined
onMounted(() => {
	unbind = runtime.bind()
})
onBeforeUnmount(() => {
	unbind?.()
	runtime.dispose()
})

defineSlots<{default: () => unknown}>()
</script>

<template>
	<slot />
	<MultiSelectPopup />
	<CommandPalette />
	<PaneModalComplex />
	<PaneModalTabs />
	<TooltipRoot />
</template>
