// src/react/components/Markdown/Markdown.tsx
import MarkdownIt from 'markdown-it'
import MarkdownItAnchor from 'markdown-it-anchor'
import MarkdownItDeflist from 'markdown-it-deflist'
import MarkdownItFootnote from 'markdown-it-footnote'
import MarkdownItTOC from 'markdown-it-toc-done-right'
import {type HTMLAttributes, useMemo} from 'react'

import {classNames} from '../../classNames'
import styles from './Markdown.module.styl'

export interface MarkdownProps extends HTMLAttributes<HTMLDivElement> {
	source?: string
	anchor?: MarkdownItAnchor.AnchorOptions
	breaks?: boolean
	html?: boolean
	langPrefix?: string
	linkify?: boolean
	toc?: Record<string, unknown>
}

export function Markdown({
	source = '',
	anchor = {},
	breaks = false,
	html = false,
	langPrefix = 'language-',
	linkify = false,
	toc = {},
	className,
	...props
}: MarkdownProps) {
	const rendered = useMemo(
		() =>
			new MarkdownIt()
				.use(MarkdownItAnchor, anchor)
				.use(MarkdownItDeflist)
				.use(MarkdownItFootnote)
				.use(MarkdownItTOC, toc)
				.set({breaks, html, langPrefix, linkify})
				.render(source),
		[anchor, breaks, html, langPrefix, linkify, source, toc]
	)

	return (
		<div
			{...props}
			className={classNames(styles.markdown, className)}
			dangerouslySetInnerHTML={{__html: rendered}}
		/>
	)
}

// packages/vue/src/Markdown/Markdown.vue
<script setup lang="ts">
import {
	type MarkdownRenderOptions,
	renderMarkdown,
} from '@tweeq/core'
import {computed} from 'vue'

const props = withDefaults(
	defineProps<MarkdownRenderOptions & {source?: string}>(),
	{
	source: '',
	anchor: () => ({}),
	breaks: false,
	html: false,
	langPrefix: 'language-',
	linkify: false,
	toc: () => ({}),
	}
)

const rendered = computed(() => renderMarkdown(props.source, props))
</script>

<template>
	<div class="MarkdownIt" data-tq-component="markdown" data-tq-part="root" v-html="rendered" />
</template>
