// packages/vue/src/Menu/Menu.vue
<script setup lang="ts">
import {
	isPointInTriangle,
	type MenuItem,
	type Point,
} from '@tweeq/core'
import {computed, ref, useTemplateRef} from 'vue'

import {BindIcon} from '../BindIcon'
import {Icon} from '../Icon'
import Popover from '../Popover/Popover.vue'
import {useThemeStore} from '../stores/theme'

export interface Props {
	items: MenuItem[]
}

const props = defineProps<Props>()

// Bubbles up when a command is chosen, so the whole menu chain can close (this
// replaces floating-vue's v-close-popper.all now that menus use Tweeq Popover).
const emit = defineEmits<{close: []}>()

function onClick(menu: MenuItem) {
	if ('perform' in menu && menu.perform) {
		menu.perform()
		emit('close')
	}
}

const theme = useThemeStore()

const hoverIndex = ref(-1)

const $menuRoot = useTemplateRef<HTMLElement>('$menuRoot')
const $lists = useTemplateRef<HTMLElement[]>('$lists')
const $childMenu = useTemplateRef<{getRoot: () => HTMLElement | null}>(
	'$childMenu'
)

// Expose the root <ul> so a parent menu can measure this submenu for its safe
// triangle (the component is multi-root, so $el isn't reliably the <ul>).
defineExpose({getRoot: () => $menuRoot.value})

const $childReference = computed<HTMLElement | null>(() => {
	if (hoverIndex.value === -1) return null

	return $lists.value?.[hoverIndex.value] ?? null
})

const childItems = computed(() => {
	const item = props.items[hoverIndex.value]
	return item && 'children' in item ? (item.children ?? null) : null
})

// --- "Safe triangle" submenu navigation ---------------------------------------
// While a submenu is open, let the cursor cut diagonally across sibling items to
// reach it without the submenu closing. Each move we test whether the cursor is
// travelling *into* the submenu: it's inside the triangle (beam) fanned from the
// previous cursor position to the submenu's near edge. While so, sibling hovers
// are ignored; the moment the cursor leaves that beam, the hovered sibling wins.
let pointer: Point = {x: 0, y: 0}
let prevPointer: Point = {x: 0, y: 0}
// Item currently under the cursor (may differ from hoverIndex while in the beam).
const candidateIndex = ref(-1)

function submenuIsOpen() {
	const cur = props.items[hoverIndex.value]
	return hoverIndex.value !== -1 && !!cur && 'children' in cur && !!cur.children
}

// The submenu's vertical edge facing the cursor (handles a left-flipped submenu).
function submenuEdge(): {c1: Point; c2: Point} | null {
	const el = $childMenu.value?.getRoot()
	if (!el) return null
	const r = el.getBoundingClientRect()
	const edgeX = r.left >= pointer.x ? r.left : r.right
	return {c1: {x: edgeX, y: r.top}, c2: {x: edgeX, y: r.bottom}}
}

// Is the cursor travelling toward the submenu — i.e. inside the beam fanned from
// the previous cursor position to the submenu's near edge?
function headingToSubmenu(at: Point): boolean {
	const e = submenuEdge()
	return !!e && isPointInTriangle(at, prevPointer, e.c1, e.c2)
}

function commitHover(index: number) {
	hoverIndex.value = index
}

function onItemEnter(index: number, e: PointerEvent) {
	candidateIndex.value = index
	pointer = {x: e.clientX, y: e.clientY}
	if (!submenuIsOpen() || !headingToSubmenu(pointer)) commitHover(index)
}

function onPointerMove(e: PointerEvent) {
	pointer = {x: e.clientX, y: e.clientY}

	// Left the beam toward the submenu → let the item the cursor is actually over
	// take over.
	if (
		submenuIsOpen() &&
		!headingToSubmenu(pointer) &&
		candidateIndex.value !== -1 &&
		candidateIndex.value !== hoverIndex.value
	) {
		commitHover(candidateIndex.value)
	}

	prevPointer = pointer
}

function onPointerLeave() {
	candidateIndex.value = -1
}

</script>

<template>
	<ul
		ref="$menuRoot"
		class="TqMenu"
		data-tq-component="menu"
		@pointermove="onPointerMove"
		@pointerleave="onPointerLeave"
		data-tq-part="root"
	>
		<template v-for="(menu, index) in items" :key="index + '_item'">
			<li
				v-if="'separator' in menu"
				ref="$lists"
				class="separator"
				data-tq-part="separator"
			/>
			<li
				v-else
				ref="$lists"
				class="menu"
				:class="{
					active: index === hoverIndex && candidateIndex === index,
					'submenu-open':
						index === hoverIndex &&
						candidateIndex !== index &&
						'children' in menu,
				}"
				:data-tq-active="
					index === hoverIndex && candidateIndex === index ? '' : undefined
				"
				:data-tq-submenu-open="
					index === hoverIndex &&
					candidateIndex !== index &&
					'children' in menu
						? ''
						: undefined
				"
				@click="onClick(menu)"
				@pointerenter="onItemEnter(index, $event)"
				data-tq-part="item"
			>
				<Icon
					v-if="menu.icon"
					class="icon"
					data-tq-part="icon"
					:icon="menu.icon"
				/>
				<span v-else />
				<div class="label-container" data-tq-part="label-container">
					<span class="label" data-tq-part="label">
						{{ menu.shortLabel ?? menu.label }}
					</span>
					<BindIcon
						v-if="'bindIcon' in menu && menu.bindIcon"
						class="bind-icon"
						data-tq-part="bind-icon"
						:icon="menu.bindIcon"
					/>
					<Icon
						v-if="'children' in menu"
						class="group-chevron"
						data-tq-part="group-chevron"
						icon="mdi:chevron-right"
					/>
				</div>
			</li>
		</template>
	</ul>
	<Popover
		v-if="$childReference && childItems"
		:reference="$childReference"
		placement="right-start"
		:open="true"
		:offset="{crossAxis: -theme.popupPadding}"
		:lightDismiss="false"
	>
		<Menu ref="$childMenu" :items="childItems" @close="emit('close')" />
	</Popover>
</template>

// src/react/components/Menu/Menu.tsx
import {
	forwardRef,
	type PointerEvent,
	useImperativeHandle,
	useRef,
	useState,
} from 'react'
import {useStore} from 'zustand'

import {
	isPointInTriangle,
	type MenuItem,
	type Point,
	themeStore,
} from '../../../core'
import {classNames} from '../../classNames'
import {BindIcon} from '../BindIcon'
import {Icon} from '../Icon'
import {Popover} from '../Popover'
import styles from './Menu.module.styl'

export interface MenuProps {
	items: MenuItem[]
	onClose?: () => void
}

export interface MenuHandle {
	getRoot(): HTMLUListElement | null
}

export const Menu = forwardRef<MenuHandle, MenuProps>(function MenuComponent(
	{items, onClose},
	forwardedRef
) {
	const popupPadding = useStore(themeStore, state => state.popupPadding)
	const [hoverIndex, setHoverIndex] = useState(-1)
	const [candidateIndex, setCandidateIndex] = useState(-1)
	const root = useRef<HTMLUListElement>(null)
	const itemElements = useRef<(HTMLLIElement | null)[]>([])
	const childMenu = useRef<MenuHandle>(null)
	const pointer = useRef<Point>({x: 0, y: 0})
	const previousPointer = useRef<Point>({x: 0, y: 0})

	useImperativeHandle(forwardedRef, () => ({getRoot: () => root.current}), [])

	const hoveredItem = items[hoverIndex]
	const childItems =
		hoveredItem && 'children' in hoveredItem ? hoveredItem.children : undefined
	const childReference =
		hoverIndex === -1 ? null : itemElements.current[hoverIndex]

	const submenuIsOpen = () => Boolean(childItems)
	const submenuEdge = (): {c1: Point; c2: Point} | null => {
		const element = childMenu.current?.getRoot()
		if (!element) return null
		const rect = element.getBoundingClientRect()
		const edgeX = rect.left >= pointer.current.x ? rect.left : rect.right
		return {
			c1: {x: edgeX, y: rect.top},
			c2: {x: edgeX, y: rect.bottom},
		}
	}
	const headingToSubmenu = (at: Point) => {
		const edge = submenuEdge()
		return Boolean(
			edge && isPointInTriangle(at, previousPointer.current, edge.c1, edge.c2)
		)
	}

	const onItemEnter = (index: number, event: PointerEvent) => {
		setCandidateIndex(index)
		pointer.current = {x: event.clientX, y: event.clientY}
		if (!submenuIsOpen() || !headingToSubmenu(pointer.current)) {
			setHoverIndex(index)
		}
	}

	const onPointerMove = (event: PointerEvent) => {
		pointer.current = {x: event.clientX, y: event.clientY}
		if (
			submenuIsOpen() &&
			!headingToSubmenu(pointer.current) &&
			candidateIndex !== -1 &&
			candidateIndex !== hoverIndex
		) {
			setHoverIndex(candidateIndex)
		}
		previousPointer.current = pointer.current
	}

	return (
		<>
			<ul
				ref={root}
				className={styles.tqMenu}
				onPointerMove={onPointerMove}
				onPointerLeave={() => setCandidateIndex(-1)}
			>
				{items.map((item, index) =>
					'separator' in item ? (
						<li
							key={`${index}_separator`}
							ref={element => {
								itemElements.current[index] = element
							}}
							className={styles.separator}
						/>
					) : (
						<li
							key={`${index}_item`}
							ref={element => {
								itemElements.current[index] = element
							}}
							className={classNames(
								styles.menu,
								index === hoverIndex &&
									candidateIndex === index &&
									styles.active,
								index === hoverIndex &&
									candidateIndex !== index &&
									'children' in item &&
									styles.submenuOpen
							)}
							onClick={() => {
								if ('perform' in item && item.perform) {
									item.perform()
									onClose?.()
								}
							}}
							onPointerEnter={event => onItemEnter(index, event)}
						>
							{item.icon ? (
								<Icon className={styles.icon} icon={item.icon} />
							) : (
								<span />
							)}
							<div className={styles.labelContainer}>
								<span className={styles.label}>
									{item.shortLabel ?? item.label}
								</span>
								{'bindIcon' in item && item.bindIcon && (
									<BindIcon className={styles.bindIcon} icon={item.bindIcon} />
								)}
								{'children' in item && (
									<Icon
										className={styles.groupChevron}
										icon="mdi:chevron-right"
									/>
								)}
							</div>
						</li>
					)
				)}
			</ul>
			{childReference && childItems && (
				<Popover
					reference={childReference}
					placement="right-start"
					open
					offset={{crossAxis: -popupPadding}}
					lightDismiss={false}
				>
					<Menu ref={childMenu} items={childItems} onClose={onClose} />
				</Popover>
			)}
		</>
	)
})
