// packages/vue/src/Viewport/Viewport.vue
<script lang="ts" setup>
import {createTweeqRuntime} from '@tweeq/dom'
import {onBeforeUnmount, onMounted} from 'vue'

import {
	provideTweeqRuntime,
	useOptionalTweeqRuntime,
} from '../runtime'

const props = withDefaults(
	defineProps<{appId?: string; initialize?: boolean}>(),
	{appId: 'viewport', initialize: true}
)
const parentRuntime = useOptionalTweeqRuntime()
const runtime = parentRuntime ?? createTweeqRuntime({appId: props.appId})
if (!parentRuntime) provideTweeqRuntime(runtime)
let unbind: (() => void) | undefined
onMounted(() => {
	if (!parentRuntime && props.initialize) unbind = runtime.bind()
})
onBeforeUnmount(() => {
	if (!parentRuntime) {
		unbind?.()
		runtime.dispose()
	}
})
</script>

<template>
	<div class="TqViewport" data-tq-component="viewport" data-tq-part="viewport">
		<slot />
	</div>
</template>

// packages/react/src/components/Viewport/Viewport.tsx
import {type HTMLAttributes} from 'react'

import {classNames} from '../../classNames'
import {
	TweeqRuntimeProvider,
	useOptionalTweeqRuntime,
	useOwnedTweeqRuntime,
} from '../../runtime'

export interface ViewportProps extends HTMLAttributes<HTMLDivElement> {
	/** App config namespace used by the standalone viewport. */
	appId?: string
}

export function Viewport({
	appId = 'viewport',
	className,
	children,
	...props
}: ViewportProps) {
	const parentRuntime = useOptionalTweeqRuntime()
	const ownedRuntime = useOwnedTweeqRuntime(appId, {}, parentRuntime)
	const content = (
		<div
			{...props}
			className={classNames('TqViewport', className)}
			data-tq-component="viewport"
			data-tq-part="viewport"
		>
			{children}
		</div>
	)
	if (parentRuntime) return content
	return (
		<TweeqRuntimeProvider runtime={ownedRuntime} bind disposeOnUnmount>
			{content}
		</TweeqRuntimeProvider>
	)
}
