// packages/react/src/components/GlslCanvas/GlslCanvas.tsx
import {drawGlslToImage, type GlslUniforms} from '@tweeq/dom'
import {
	forwardRef,
	type ImgHTMLAttributes,
	useEffect,
	useImperativeHandle,
	useRef,
} from 'react'

import {useResizeObserver} from '../../hooks'

const DEFAULT_FRAGMENT = `
	precision mediump float;
	varying vec2 uv;
	void main() { gl_FragColor = vec4(uv, 0, 1); }
`

export interface GlslCanvasProps
	extends Omit<ImgHTMLAttributes<HTMLImageElement>, 'src'> {
	fragmentString?: string
	uniforms?: GlslUniforms
}

export const GlslCanvas = forwardRef<HTMLImageElement, GlslCanvasProps>(
	function GlslCanvasComponent(
		{
			fragmentString = DEFAULT_FRAGMENT,
			uniforms = {},
			className,
			alt = '',
			...props
		},
		forwardedRef
	) {
		const image = useRef<HTMLImageElement>(null)
		useImperativeHandle(forwardedRef, () => image.current!, [])
		useResizeObserver(image, () => {
			const element = image.current
			if (element) drawGlslToImage(element, fragmentString, uniforms)
		})

		useEffect(() => {
			const element = image.current
			if (!element) return
			return drawGlslToImage(element, fragmentString, uniforms)
		}, [fragmentString, uniforms])

		return (
			<img
				{...props}
				ref={image}
				alt={alt}
				className={className}
				data-tq-component="glsl-canvas"
				data-tq-part="image"
			/>
		)
	}
)

// packages/vue/src/GlslCanvas/GlslCanvas.vue
<script lang="ts" setup>
import {drawGlslToImage, type GlslUniforms} from '@tweeq/dom'
import {useResizeObserver} from '@vueuse/core'
import {onUnmounted, useTemplateRef, watch} from 'vue'

export interface GlslCanvasProps {
	fragmentString?: string
	uniforms?: GlslUniforms
}

const props = withDefaults(defineProps<GlslCanvasProps>(), {
	fragmentString: `
		precision mediump float;
		varying vec2 uv;
		void main() { gl_FragColor = vec4(uv, 0, 1); }`,
	uniforms: () => ({}),
})

const $img = useTemplateRef('$img')

let cancelDraw: (() => void) | undefined
function draw() {
	cancelDraw?.()
	if ($img.value) {
		cancelDraw = drawGlslToImage(
			$img.value,
			props.fragmentString,
			props.uniforms
		)
	}
}

watch(
	() => [props.fragmentString, props.uniforms] as const,
	draw,
	{immediate: true, flush: 'post'}
)
useResizeObserver($img, draw)
onUnmounted(() => cancelDraw?.())
</script>

<template>
	<img ref="$img" class="GlslCanvas" alt="" data-tq-component="glsl-canvas" data-tq-part="image" />
</template>
