// packages/vue/src/MultiSelectPopup/MultiSelectPopup.vue
<script setup lang="ts">
import {vec2} from 'linearly'
import {computed, onMounted, useTemplateRef, watchEffect} from 'vue'

import {Icon} from '../Icon'
import {MultiSelectType, useMultiSelectStore} from '../stores/multiSelect'
import {addAnchorName} from '@tweeq/dom'
import MultiSelectButton from './MultiSelectButton.vue'
import MultiSelectPad from './MultiSelectPad.vue'

const multiSelect = useMultiSelectStore()

const selectedTypes = computed(() =>
	multiSelect.selectedInputs.map(i => i.type)
)

const $root = useTemplateRef('$root')

onMounted(() => {
	if (!$root.value) return
	multiSelect.setPopupEl($root.value)
})

// Anchor the popup under the focused input via CSS Anchor Positioning (no
// floating-ui). The browser keeps it positioned on scroll/resize. anchor() is
// passed inline rather than in the stylus block, which would try to parse it as
// a stylus function call.
const ANCHOR_NAME = '--tq-multi-select-anchor'

const anchorStyle = {
	positionAnchor: ANCHOR_NAME,
	top: 'anchor(bottom)',
	right: 'anchor(right)',
}

watchEffect(onCleanup => {
	const el = multiSelect.focusedElement
	if (!el) return
	onCleanup(addAnchorName(el, ANCHOR_NAME))
})

type MultiSelectAction = {
	enabled: (types: MultiSelectType[]) => boolean
	icon: string
} & (
	| {
			type: 'slider'
			updator: (px: number) => (values: any[]) => any[]
	  }
	| {
			type: 'pad'
			updator: (delta: vec2) => (values: any[]) => any[]
	  }
	| {
			type: 'button'
			updator: (values: any[]) => any[]
	  }
)

const actions: MultiSelectAction[] = [
	{
		type: 'slider',
		enabled: types => types.every(t => t === 'number'),
		updator: (px: number) => (values: number[]) =>
			values.map((v, i) => v + px * (multiSelect.selectedInputs[i].speed ?? 1)),
		icon: 'material-symbols:add',
	},
	{
		type: 'slider',
		enabled: types => types.every(t => t === 'number'),
		updator: (px: number) => (values: number[]) =>
			values.map(v => v * (px / 100 + 1)),
		icon: 'mdi:multiply',
	},
	{
		type: 'pad',
		enabled: types => types.length === 2 && types.every(t => t === 'number'),
		updator: (delta: vec2) => (values: number[]) =>
			vec2.add(
				values as unknown as vec2,
				vec2.mul(delta, [
					multiSelect.selectedInputs[0].speed ?? 1,
					-(multiSelect.selectedInputs[1].speed ?? 1),
				])
			) as unknown as number[],
		icon: 'mdi:dots-grid',
	},
	{
		type: 'button',
		enabled: types =>
			types.length === 2 && types[0] !== 'boolean' && types[0] === types[1],
		updator: values => values.reverse(),
		icon: 'material-symbols:swap-vert',
	},
]

const enabledActions = computed(() =>
	actions.filter(a => a.enabled(selectedTypes.value))
)

const visible = computed(() => {
	if (multiSelect.selectedInputs.length <= 1) return false
	if (enabledActions.value.length === 0) return false

	return true
})

watchEffect(() => {
	$root.value?.togglePopover(visible.value)
})
</script>

<template>
	<div
		ref="$root"
		:class="{visible}"
		class="TqMultiSelectPopup"
		:style="anchorStyle"
		popover="manual"
	>
		<Icon class="tune-icon" icon="lsicon:control-filled" />
		<div class="actions">
			<template v-for="action in enabledActions" :key="action.icon">
				<MultiSelectPad
					v-if="action.type === 'slider' || action.type === 'pad'"
					:type="action.type"
					:updator="action.updator"
					:icon="action.icon"
				/>
				<MultiSelectButton
					v-else-if="action.type === 'button'"
					:updator="action.updator"
					:icon="action.icon"
				/>
			</template>
		</div>
	</div>
</template>

<style lang="stylus" scoped>
@import '../common.styl'

reset-viewport('.TqMultiSelectPopup')

.TqMultiSelectPopup
	position fixed
	inset auto
	popup-style()
	margin 3px 0
	z-index 1000
	visibility hidden
	padding 0
	border-color var(--tq-color-accent)
	box-shadow none
	overflow hidden
	hover-transition(width, height, border-radius)
	box-sizing border-box

	&:not(:hover)
		width var(--tq-icon-size)
		height var(--tq-icon-size)
		border-radius 99px

	&.visible
		visibility visible

.tune-icon
	position absolute
	top -1px
	left -1px
	width var(--tq-icon-size)
	height var(--tq-icon-size)
	scale .8
	color var(--tq-color-accent)
	opacity 1
	pointer-events none

	.TqMultiSelectPopup:hover &
		opacity 0

.actions
	display flex
	flex-direction row
	padding 2px
	gap var(--tq-gap-group)
	opacity 0

	.TqMultiSelectPopup:hover &
		opacity 1
</style>

// src/react/components/MultiSelectPopup/MultiSelectPopup.tsx
import './MultiSelectPopup.global.styl'

import {type CSSProperties, useEffect, useMemo, useRef} from 'react'
import {useStore} from 'zustand'

import {
	addAnchorName,
	multiSelectStore,
	type MultiSelectType,
} from '../../../core'
import {classNames} from '../../classNames'
import {Icon} from '../Icon'
import {MultiSelectButton} from './MultiSelectButton'
import {MultiSelectPad} from './MultiSelectPad'
import styles from './MultiSelectPopup.module.styl'

const ANCHOR_NAME = '--tq-multi-select-anchor'

export function MultiSelectPopup() {
	const root = useRef<HTMLDivElement>(null)
	useStore(multiSelectStore)
	const state = multiSelectStore.getState()
	const selected = state.getSelectedInputs()
	const types = selected.map(input => input.type)
	const focusedElement = state.getFocusedElement()

	const actions = useMemo(
		() => [
			{
				type: 'slider' as const,
				enabled: (current: MultiSelectType[]) =>
					current.every(type => type === 'number'),
				update: (pixels: number) => (values: number[]) =>
					values.map(
						(value, index) => value + pixels * (selected[index]?.speed ?? 1)
					),
				icon: 'material-symbols:add',
			},
			{
				type: 'slider' as const,
				enabled: (current: MultiSelectType[]) =>
					current.every(type => type === 'number'),
				update: (pixels: number) => (values: number[]) =>
					values.map(value => value * (pixels / 100 + 1)),
				icon: 'mdi:multiply',
			},
			{
				type: 'pad' as const,
				enabled: (current: MultiSelectType[]) =>
					current.length === 2 && current.every(type => type === 'number'),
				update: (delta: readonly [number, number]) => (values: number[]) => [
					values[0] + delta[0] * (selected[0]?.speed ?? 1),
					values[1] - delta[1] * (selected[1]?.speed ?? 1),
				],
				icon: 'mdi:dots-grid',
			},
			{
				type: 'button' as const,
				enabled: (current: MultiSelectType[]) =>
					current.length === 2 &&
					current[0] !== 'boolean' &&
					current[0] === current[1],
				update: (values: number[]) => [...values].reverse(),
				icon: 'material-symbols:swap-vert',
			},
		],
		[selected]
	)
	const enabled = actions.filter(action => action.enabled(types))
	const visible = selected.length > 1 && enabled.length > 0

	useEffect(() => {
		if (!focusedElement) return
		return addAnchorName(focusedElement, ANCHOR_NAME)
	}, [focusedElement])
	useEffect(() => {
		const element = root.current
		if (!element) return
		multiSelectStore.getState().setPopupEl(element)
		try {
			if (visible && !element.matches(':popover-open')) element.showPopover()
			else if (!visible && element.matches(':popover-open'))
				element.hidePopover()
		} catch {
			// Unsupported native popover.
		}
		return () => multiSelectStore.getState().setPopupEl(null)
	}, [visible])

	return (
		<div
			ref={root}
			className={classNames(
				'TqMultiSelectPopup',
				styles.popup,
				visible && styles.visible
			)}
			style={
				{
					positionAnchor: ANCHOR_NAME,
					top: 'anchor(bottom)',
					right: 'anchor(right)',
				} as CSSProperties
			}
			popover="manual"
		>
			<Icon className={styles.tuneIcon} icon="lsicon:control-filled" />
			<div className={styles.actions}>
				{enabled.map(action =>
					action.type === 'button' ? (
						<MultiSelectButton
							key={action.icon}
							icon={action.icon}
							update={action.update}
						/>
					) : (
						<MultiSelectPad
							key={action.icon}
							type={action.type}
							icon={action.icon}
							update={action.update}
						/>
					)
				)}
			</div>
		</div>
	)
}
