// packages/react/src/components/PaneZUI/PaneZUI.tsx
import {getZuiDotState, getZuiVisibleRect} from '@tweeq/core'
import {bindZuiGestures} from '@tweeq/dom'
import {mat2d, type vec2} from 'linearly'
import {
	type CSSProperties,
	type HTMLAttributes,
	useEffect,
	useRef,
	useState,
} from 'react'

import {useBndr, useElementBounding} from '../../hooks'

export type VisibleRect = readonly [vec2, vec2]

export interface PaneZUIProps
	extends Omit<HTMLAttributes<HTMLDivElement>, 'onChange'> {
	transform?: mat2d
	onChangeTransform?: (transform: mat2d) => void
	onChangeVisibleRect?: (rect: VisibleRect) => void
	onChangeSize?: (size: vec2) => void
	background?: 'dots'
}

export function PaneZUI({
	transform,
	onChangeTransform,
	onChangeVisibleRect,
	onChangeSize,
	background,
	children,
	className,
	...props
}: PaneZUIProps) {
	const root = useRef<HTMLDivElement>(null)
	const bounds = useElementBounding(root)
	const [local, setLocal] = useState<mat2d>(() => transform ?? mat2d.I)
	const localRef = useRef(local)
	localRef.current = local
	const callback = useRef(onChangeTransform)
	callback.current = onChangeTransform

	useEffect(() => {
		if (transform && !mat2d.approx(transform, localRef.current))
			setLocal(transform)
	}, [transform])
	useEffect(() => {
		onChangeSize?.([bounds.width, bounds.height])
		onChangeVisibleRect?.(getZuiVisibleRect(local, [bounds.width, bounds.height]))
	}, [bounds.height, bounds.width, local, onChangeSize, onChangeVisibleRect])

	useBndr(root, element => {
		const apply = (delta: mat2d) => {
			const next = mat2d.mul(delta, localRef.current)
			localRef.current = next
			setLocal(next)
			callback.current?.(next)
		}
		bindZuiGestures(element, apply)
	})

	const dots = getZuiDotState(local)

	return (
		<div
			{...props}
			ref={root}
			className={className}
			data-tq-component="pane-zui"
			data-tq-part="root"
		>
			{background === 'dots' && (
				<div
					data-tq-part="dots"
					style={{
						opacity: dots.opacity,
						backgroundPosition: `${dots.position[0]}px ${dots.position[1]}px`,
						backgroundSize: `${dots.size[0]}px ${dots.size[1]}px`,
					}}
				/>
			)}
			<div
				data-tq-part="transform"
				style={{transform: `matrix(${local.join(',')})`} as CSSProperties}
			>
				{children}
			</div>
		</div>
	)
}

// packages/vue/src/PaneZUI/PaneZUI.vue
<script setup lang="ts">
import {
	getZuiDotState,
	getZuiVisibleRect,
	type Rect,
} from '@tweeq/core'
import {useElementBounding} from '@vueuse/core'
import {mat2d, type vec2} from 'linearly'
import {computed, shallowRef, useTemplateRef, watch, watchEffect} from 'vue'

import {useZUI} from '../use/useZUI'

const props = defineProps<{
	transform?: mat2d
	background?: 'dots'
}>()

const emit = defineEmits<{
	'update:transform': [mat2d]
	'update:visibleRect': [Rect]
	'update:size': [vec2]
}>()

const $root = useTemplateRef('$root')

const {width: rootWidth, height: rootHeight} = useElementBounding($root)

const transformLocal = shallowRef(props.transform ?? mat2d.I)

const size = computed<vec2>(() => {
	return [rootWidth.value, rootHeight.value]
})

watchEffect(() => {
	emit('update:size', size.value)
})

watch(
	() => props.transform,
	transform => {
		transformLocal.value = transform ?? mat2d.I
	},
	{immediate: true}
)

watch(transformLocal, local => {
	if (local === props.transform) return
	emit('update:transform', local)
})

watchEffect(() => {
	emit('update:visibleRect', getZuiVisibleRect(transformLocal.value, size.value))
})

useZUI($root, delta => {
	transformLocal.value = mat2d.mul(delta, transformLocal.value)
})

const dotStyles = computed(() => {
	const dots = getZuiDotState(transformLocal.value)

	return {
		opacity: `${dots.opacity * 100}%`,
		backgroundPosition: `${dots.position[0]}px ${dots.position[1]}px`,
		backgroundSize: `${dots.size[0]}px ${dots.size[1]}px`,
	}
})

const transformStyles = computed(() => {
	return {
		transform: `matrix(${transformLocal.value.join(',')})`,
	}
})
</script>

<template>
	<div
		ref="$root"
		class="TqPaneZUI"
		:class="{dots: background === 'dots'}"
		data-tq-component="pane-zui"
		data-tq-part="root"
	>
		<div
			v-if="background === 'dots'"
			class="dots"
			data-tq-part="dots"
			:style="dotStyles"
		/>
		<div class="transform" :style="transformStyles" data-tq-part="transform">
			<slot />
		</div>
	</div>
</template>
