// packages/vue/src/InputCubicBezier/InputCubicBezier.vue
<script lang="ts" setup>
import {getCubicBezierPath, type CubicBezierValue} from '@tweeq/core'
import {computed, ref, useTemplateRef} from 'vue'

import {Popover} from '../Popover'
import type {InputEmits} from '../types'
import InputCubicBezierPicker from './InputCubicBezierPicker.vue'
import type {InputCubicBezierProps} from './types'

const props = defineProps<InputCubicBezierProps>()

const emit = defineEmits<
	InputEmits & {'update:modelValue': [CubicBezierValue]}
>()

defineOptions({
	inheritAttrs: false,
})

const $button = useTemplateRef('$button')
const open = ref(false)

const easingPath = computed(() => getCubicBezierPath(props.modelValue))
</script>

<template>
	<button
		ref="$button"
		class="TqInputCubicBezier"
		:class="{open}"
		v-bind="$attrs"
		type="button"
		:disabled="props.disabled"
		:aria-invalid="props.invalid || undefined"
		:aria-expanded="open"
		:inline-position="props.inlinePosition"
		:block-position="props.blockPosition"
		data-tq-component="input-cubic-bezier"
		:data-tq-open="open ? '' : undefined"
		data-tq-part="root"
		@click="open = true"
		@focus="emit('focus')"
		@blur="emit('blur')"
	>
		<svg class="icon" viewBox="0 0 1 1" data-tq-part="icon">
			<path :d="easingPath" data-tq-part="path" />
		</svg>
	</button>
	<Popover v-model:open="open" :reference="$button">
		<div
			class="floating"
			data-tq-component="input-cubic-bezier-floating"
			data-tq-part="floating"
		>
			<InputCubicBezierPicker
				:modelValue="modelValue"
				:disabled="props.disabled"
				@update:modelValue="emit('update:modelValue', $event)"
				@confirm="emit('confirm')"
			/>
		</div>
	</Popover>
</template>

// src/react/components/InputCubicBezier/InputCubicBezier.tsx
import {type ButtonHTMLAttributes, type CSSProperties, useState} from 'react'

import {
	type CubicBezierValue,
	getCubicBezierPath,
	type InputBoxProps,
	type InputEvents,
} from '../../../core'
import {classNames} from '../../classNames'
import {Popover} from '../Popover'
import styles from './InputCubicBezier.module.styl'
import {InputCubicBezierPicker} from './InputCubicBezierPicker'

export interface InputCubicBezierProps
	extends InputBoxProps,
		InputEvents,
		Omit<
			ButtonHTMLAttributes<HTMLButtonElement>,
			'onBlur' | 'onChange' | 'onFocus' | 'value'
		> {
	value: CubicBezierValue
	onChange?: (value: CubicBezierValue) => void
}

export function InputCubicBezier({
	value,
	onChange,
	onConfirm,
	inlinePosition,
	blockPosition,
	className,
	...props
}: InputCubicBezierProps) {
	const [button, setButton] = useState<HTMLButtonElement | null>(null)
	const [open, setOpen] = useState(false)

	return (
		<>
			<button
				{...props}
				ref={setButton}
				type={props.type ?? 'button'}
				className={classNames(
					styles.inputCubicBezier,
					open && styles.open,
					className
				)}
				data-inline-position={inlinePosition}
				data-block-position={blockPosition}
				onClick={() => setOpen(true)}
			>
				<svg className={styles.icon} viewBox="0 0 1 1" aria-hidden="true">
					<path d={getCubicBezierPath(value)} />
				</svg>
			</button>
			<Popover open={open} reference={button} onChangeOpen={setOpen}>
				<div className={styles.floating}>
					<InputCubicBezierPicker
						value={value}
						onChange={onChange}
						onConfirm={onConfirm}
					/>
				</div>
			</Popover>
		</>
	)
}

export function cubicBezierStyle(value: CubicBezierValue): CSSProperties {
	return {transitionTimingFunction: `cubic-bezier(${value.join(',')})`}
}
