// packages/react/src/components/Ruler/Ruler.tsx
import {
	getRulerDefaultScales,
	getRulerPixelsPerUnit,
	getRulerScaleOffset,
	getRulerValueAtPixel,
	type RulerScale,
} from '@tweeq/core'
import * as Bndr from 'bndr-js'
import {type vec2} from 'linearly'
import {type HTMLAttributes, type ReactNode, useRef} from 'react'

import {classNames} from '../../classNames'
import {useBndr, useElementBounding} from '../../hooks'

export interface RulerProps
	extends Omit<HTMLAttributes<HTMLDivElement>, 'onDrag'> {
	range: vec2
	scales?: RulerScale[]
	onDrag?: (value: number) => void
	children?: ReactNode
}

export function Ruler({
	range,
	scales,
	onDrag,
	children,
	className,
	style,
	...props
}: RulerProps) {
	const root = useRef<HTMLDivElement>(null)
	const {width} = useElementBounding(root)
	const pixelsPerUnit = getRulerPixelsPerUnit(width, range)
	const renderedScales = scales ?? getRulerDefaultScales(range)

	useBndr(
		root,
		element => {
			Bndr.pointer(element)
				.drag({pointerCapture: true, coordinate: 'offset'})
				.on(drag => {
					onDrag?.(getRulerValueAtPixel(drag.current[0], width, range))
				})
		},
		[onDrag, range[0], range[1], width]
	)

	return (
		<div
			{...props}
			ref={root}
			className={classNames('TqRuler', className)}
			style={{
				...style,
				backgroundSize: `${pixelsPerUnit}px 100%`,
				backgroundPosition: `${-range[0] * pixelsPerUnit}px 0`,
			}}
			data-tq-component="ruler"
			data-tq-part="root"
		>
			<div data-tq-part="content">{children}</div>
			{renderedScales.map(scale => (
				<div
					key={scale.value}
					style={{
						transform: `translateX(${getRulerScaleOffset(scale.value, range, pixelsPerUnit)}px)`,
						opacity: scale.opacity ?? 1,
					}}
					data-tq-part="scale"
				>
					{scale.label ?? scale.value}
				</div>
			))}
		</div>
	)
}

// packages/vue/src/Ruler/Ruler.vue
<script setup lang="ts">
import {
	getRulerDefaultScales,
	getRulerPixelsPerUnit,
	getRulerScaleOffset,
	getRulerValueAtPixel,
	type RulerScale,
} from '@tweeq/core'
import {type MaybeElementRef, useElementBounding} from '@vueuse/core'
import * as Bndr from 'bndr-js'
import {type vec2} from 'linearly'
import {computed, ref} from 'vue'

import {useBndr} from '../use/useBndr'

const props = defineProps<{
	range: vec2
	scales?: RulerScale[]
}>()

const emit = defineEmits<{
	drag: [value: number]
}>()

const $root: MaybeElementRef = ref(null)

const {width: rootWidth} = useElementBounding($root)

const pixelsPerUnit = computed(
	() => getRulerPixelsPerUnit(rootWidth.value, props.range)
)

const rootStyle = computed(() => ({
	'background-size': `${pixelsPerUnit.value}px 100%`,
	'background-position': `${-props.range[0] * pixelsPerUnit.value}px 0`,
}))

const _scales = computed<RulerScale[]>(() => {
	return props.scales ?? getRulerDefaultScales(props.range)
})

function scaleToStyle(scale: RulerScale) {
	return {
		transform: `translateX(${toPixels(scale.value)}px)`,
		opacity: scale.opacity ?? 1,
	}
}

function toPixels(value: number) {
	return getRulerScaleOffset(value, props.range, pixelsPerUnit.value)
}

useBndr($root, el => {
	Bndr.pointer(el)
		.drag({pointerCapture: true, coordinate: 'offset'})
		.on(d => {
			const x = d.current[0]
			const value = getRulerValueAtPixel(x, rootWidth.value, props.range)
			emit('drag', value)
		})
})
</script>
<template>
	<div
		ref="$root"
		class="TqRuler"
		:style="rootStyle"
		data-tq-component="ruler"
		data-tq-part="root"
	>
		<div class="content" data-tq-part="content">
			<slot />
		</div>
		<div
			v-for="scale in _scales"
			:key="scale.value"
			class="scale"
			:style="scaleToStyle(scale)"
			data-tq-part="scale"
		>
			{{ scale.label ?? scale.value }}
		</div>
	</div>
</template>
