// packages/vue/src/InputButtonToggle/InputButtonToggle.vue
<script lang="ts" setup>
import {Icon} from '../Icon'
import {InputButtonToggleProps} from './types'

const model = defineModel<boolean>({required: true})

defineProps<InputButtonToggleProps>()
</script>

<template>
	<!--
		@mousedown.prevent keeps a mouse click from focusing the button (the click
		still toggles). Without it the button retains focus after a click and a
		later Enter/Space flips it again unexpectedly. Keyboard (Tab) focus is
		unaffected, so keyboard toggling still works — matching :focus-visible.
	-->
	<button
		class="TqInputButtonToggle"
		:class="{checked: model}"
		:inline-position="inlinePosition"
		:block-position="blockPosition"
		:disabled="!!disabled"
		:aria-invalid="invalid || undefined"
		:aria-pressed="model"
		data-tq-component="input-button-toggle"
		data-tq-part="root"
		@mousedown.prevent
		@click="model = !model"
	>
		<Icon v-if="icon" class="icon" :icon="icon" data-tq-part="icon" />
		<span v-if="label" class="label" data-tq-part="label">{{ label }}</span>
	</button>
</template>

// packages/react/src/components/InputButtonToggle/InputButtonToggle.tsx
import type {InputBoxProps} from '@tweeq/core'
import {type ButtonHTMLAttributes} from 'react'

import {Icon} from '../Icon'

export interface InputButtonToggleProps
	extends InputBoxProps,
		Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onChange' | 'value'> {
	value: boolean
	onChange?: (value: boolean) => void
	icon?: string
	label?: string
}

export function InputButtonToggle({
	value,
	onChange,
	icon,
	label,
	inlinePosition,
	blockPosition,
	disabled,
	invalid,
	className,
	onMouseDown,
	onClick,
	...props
}: InputButtonToggleProps) {
	return (
		<button
			{...props}
			className={className}
			inline-position={inlinePosition}
			block-position={blockPosition}
			disabled={Boolean(disabled)}
			aria-invalid={invalid || undefined}
			aria-pressed={value}
			data-tq-component="input-button-toggle"
			data-tq-part="root"
			onMouseDown={event => {
				onMouseDown?.(event)
				if (!event.defaultPrevented) event.preventDefault()
			}}
			onClick={event => {
				onClick?.(event)
				if (!event.defaultPrevented) onChange?.(!value)
			}}
		>
			{icon && <Icon icon={icon} data-tq-part="icon" />}
			{label && <span data-tq-part="label">{label}</span>}
		</button>
	)
}
