// packages/vue/src/InputColor/InputColor.vue
<script setup lang="ts">
import {useElementSize} from '@vueuse/core'
import chroma from 'chroma-js'
import {computed, ref, useTemplateRef} from 'vue'

import {InputGroup} from '../InputGroup'
import {InputNumber} from '../InputNumber'
import {InputString} from '../InputString'
import {useThemeStore} from '../stores/theme'
import {InputEmits} from '../types'
import * as V from '@tweeq/core/validator'
import InputColorPad from './InputColorPad.vue'
import type {InputColorProps} from './types'

const model = defineModel<string>({required: true})
const props = defineProps<InputColorProps>()
const emit = defineEmits<InputEmits>()

const theme = useThemeStore()

const $root = useTemplateRef('$root')
const {width} = useElementSize($root)

const showColorCode = computed(() => width.value > theme.inputHeight * 3.5)

const padTweaking = ref(false)

const color = computed(() => {
	if (chroma.valid(model.value)) {
		return chroma(model.value)
	}

	return chroma('black')
})

const opaqueColor = computed(() => color.value.alpha(1).hex())

const alpha = computed(() => color.value.alpha() * 100)

function onInputOpaqueColor(value: string) {
	const color = chroma(value)

	if (color.alpha() * 100 !== alpha.value) {
		model.value = value
	} else {
		model.value = color.alpha(alpha.value / 100).hex()
	}
}

function onUpdateAlpha(value: number) {
	model.value = color.value.alpha(value / 100).hex()
}
</script>

<template>
<InputGroup
		ref="$root"
		class="TqInputColor"
		component="input-color"
		:inline-position="props.inlinePosition"
		:block-position="props.blockPosition"
		data-tq-part="root"
	>
		<InputColorPad
			v-bind="props"
			v-model="model"
			v-model:tweaking="padTweaking"
			:class="{'only-pad': !showColorCode}"
			:data-tq-layout="!showColorCode ? 'only-pad' : undefined"
			data-tq-part="pad"
			:inlinePosition="showColorCode ? 'start' : undefined"
			@focus="emit('focus')"
			@blur="emit('blur')"
			@confirm="emit('confirm')"
		/>
		<InputString
			v-if="showColorCode"
			class="color-code"
			:class="{'pad-tweaking': padTweaking}"
			:data-tq-pad-tweaking="padTweaking ? '' : undefined"
			data-tq-part="color-code"
			font="monospace"
			:modelValue="opaqueColor"
			:validator="V.colorCode"
			:disabled="props.disabled"
			:invalid="props.invalid"
			:inlinePosition="props.alpha ? 'middle' : 'end'"
			@update:modelValue="onInputOpaqueColor"
			@focus="emit('focus')"
			@blur="emit('blur')"
			@confirm="emit('confirm')"
		/>
		<InputNumber
			v-if="props.alpha && showColorCode"
			class="alpha"
			data-tq-part="alpha"
			:modelValue="alpha"
			suffix="%"
			:min="0"
			:max="100"
			:disabled="props.disabled"
			:invalid="props.invalid"
			inlinePosition="end"
			@update:modelValue="onUpdateAlpha"
			@focus="emit('focus')"
			@blur="emit('blur')"
			@confirm="emit('confirm')"
		/>
	</InputGroup>
</template>

// packages/react/src/components/InputColor/InputColor.tsx
import {
	type ColorPickerComponent,
	type InputBoxProps,
	type InputEvents,
	validator,
} from '@tweeq/core'
import {themeStore} from '@tweeq/dom'
import chroma from 'chroma-js'
import {type HTMLAttributes, useRef, useState} from 'react'
import {useStore} from 'zustand'

import {useElementBounding} from '../../hooks'
import {InputGroup} from '../InputGroup'
import {InputNumber} from '../InputNumber'
import {InputString} from '../InputString'
import {InputColorPad} from './InputColorPad'

export interface InputColorProps
	extends InputBoxProps,
		InputEvents,
		Omit<HTMLAttributes<HTMLDivElement>, 'onBlur' | 'onChange' | 'onFocus'> {
	value: string
	onChange?: (value: string) => void
	alpha?: boolean
	pickers?: readonly ColorPickerComponent[]
	presets?: readonly string[]
}

export function InputColor({
	value,
	onChange,
	alpha: alphaEnabled = true,
	pickers,
	presets,
	disabled,
	invalid,
	inlinePosition,
	blockPosition,
	onFocus,
	onBlur,
	onConfirm,
	className,
	...props
}: InputColorProps) {
	const root = useRef<HTMLDivElement>(null)
	const {width} = useElementBounding(root)
	const inputHeight = useStore(themeStore, state => state.inputHeight)
	const [padTweaking, setPadTweaking] = useState(false)
	const parsed = chroma.valid(value) ? chroma(value) : chroma('black')
	const opaqueColor = parsed.alpha(1).hex()
	const alpha = parsed.alpha() * 100
	const showColorCode = width > inputHeight * 3.5

	return (
		<InputGroup
			{...props}
			ref={root}
			className={className}
			data-inline-position={inlinePosition}
			data-block-position={blockPosition}
			data-tq-component="input-color"
			data-tq-part="root"
		>
			<InputColorPad
				data-tq-layout={!showColorCode ? 'only-pad' : undefined}
				data-tq-part="pad"
				value={value}
				onChange={onChange}
				alpha={alphaEnabled}
				pickers={pickers}
				presets={presets}
				disabled={disabled}
				invalid={invalid}
				onChangeTweaking={setPadTweaking}
				onFocus={onFocus}
				onBlur={onBlur}
				onConfirm={onConfirm}
			/>
			{showColorCode && (
				<InputString
					data-tq-pad-tweaking={padTweaking ? '' : undefined}
					data-tq-part="color-code"
					font="monospace"
					value={opaqueColor}
					validator={validator.colorCode}
					disabled={disabled}
					invalid={invalid}
					onChange={next => {
						const nextColor = chroma(next)
						onChange?.(
							nextColor.alpha() * 100 !== alpha
								? next
								: nextColor.alpha(alpha / 100).hex()
						)
					}}
					onFocus={onFocus}
					onBlur={onBlur}
					onConfirm={onConfirm}
				/>
			)}
			{alphaEnabled && showColorCode && (
				<InputNumber
					data-tq-part="alpha"
					value={alpha}
					min={0}
					max={100}
					suffix="%"
					disabled={disabled}
					invalid={invalid}
					onChange={next => onChange?.(parsed.alpha(next / 100).hex())}
					onFocus={onFocus}
					onBlur={onBlur}
					onConfirm={onConfirm}
				/>
			)}
		</InputGroup>
	)
}
