// packages/vue/src/InputColor/InputColorChannelPad.vue
<script lang="ts" setup>
import {vec2} from 'linearly'
import {computed, useTemplateRef} from 'vue'

import {GlslCanvas} from '../GlslCanvas'
import {useDrag} from '../use/useDrag'
import {toPercent} from '@tweeq/core'
import FragmentString from '@tweeq/dom/shaders/pad.frag'
import {type ColorChannel, colorChannelToIndex, HSVA} from './types'
import {
	getHSVAChannel,
	hsva2hex,
	setHSVAChannel,
	tweakHSVAChannel,
} from './utils'

interface Props {
	axes: readonly [ColorChannel, ColorChannel]
	modelValue: HSVA
	disabled?: boolean
}

const props = defineProps<Props>()

const emit = defineEmits<{
	'update:modelValue': [HSVA]
}>()

const $root = useTemplateRef('$root')

let local: HSVA
// let isRelative = false

const {
	dragging: sliderTweaking,
	left,
	top,
	right,
	bottom,
	xy,
} = useDrag($root, {
	disabled: computed(() => props.disabled),
	dragDelaySeconds: 0,
	onDragStart({left, right, top, bottom, xy}, event) {
		local = props.modelValue

		const isAbsolute = event.target === $root.value

		if (isAbsolute) {
			const values = vec2.invlerp([left, bottom], [right, top], xy)

			local = setHSVAChannel(local, props.axes[0], values[0])
			local = setHSVAChannel(local, props.axes[1], values[1])

			emit('update:modelValue', local)
		}
	},
	onDrag({xy, initial, width, height}) {
		let newLocal = {...local}

		const delta = vec2.div(vec2.sub(xy, initial), [width, -height])

		newLocal = tweakHSVAChannel(newLocal, props.axes[0], delta[0])
		newLocal = tweakHSVAChannel(newLocal, props.axes[1], delta[1])

		emit('update:modelValue', newLocal)
	},
})

const tweakingInside = computed(() => {
	return (
		sliderTweaking.value &&
		left.value <= xy.value[0] &&
		right.value >= xy.value[0] &&
		top.value <= xy.value[1] &&
		bottom.value >= xy.value[1]
	)
})

const uniforms = computed(() => {
	const {h, s, v, a} = props.modelValue
	return {
		hsva: [h, s, v, a],
		axes: props.axes.map(colorChannelToIndex),
	}
})

const circleStyle = computed(() => {
	const x = getHSVAChannel(props.modelValue, props.axes[0])
	const y = getHSVAChannel(props.modelValue, props.axes[1])

	return {
		left: toPercent(x),
		bottom: toPercent(y),
		background: hsva2hex({...props.modelValue, a: 1}),
	}
})
</script>

<template>
	<div
		ref="$root"
		class="TqInputColorChannelPad"
		data-tq-component="input-color-channel-pad"
		data-tq-part="root"
		:style="{cursor: tweakingInside ? 'none' : undefined}"
	>
		<GlslCanvas
			class="canvas"
			data-tq-part="canvas"
			:fragmentString="FragmentString"
			:uniforms="uniforms"
		/>
		<div
			class="circle"
			:class="{tweaking: sliderTweaking}"
			:data-tq-tweaking="sliderTweaking ? '' : undefined"
			data-tq-part="handle"
			:style="circleStyle"
		/>
	</div>
</template>

// packages/react/src/components/InputColor/InputColorChannelPad.tsx
import {
	type ColorChannel,
	colorChannelToIndex,
	getHSVAChannel,
	type HSVA,
	hsva2hex,
	setHSVAChannel,
	toPercent,
	tweakHSVAChannel,
} from '@tweeq/core'
import PadFragmentString from '@tweeq/dom/shaders/pad.frag'
import {type CSSProperties, useMemo, useRef} from 'react'

import {useDrag} from '../../hooks'
import {GlslCanvas} from '../GlslCanvas'

export interface InputColorChannelPadProps {
	value: HSVA
	onChange?: (value: HSVA) => void
	axes: readonly [ColorChannel, ColorChannel]
	disabled?: boolean
}

export function InputColorChannelPad({
	value,
	onChange,
	axes,
	disabled,
}: InputColorChannelPadProps) {
	const root = useRef<HTMLDivElement>(null)
	const local = useRef(value)
	const current = useRef({value, onChange, axes})
	current.current = {value, onChange, axes}
	const dragOptions = useMemo(
		() => ({
			disabled: () => Boolean(disabled),
			dragDelaySeconds: 0,
			onDragStart: (
				state: {
					xy: readonly [number, number]
					left: number
					right: number
					top: number
					bottom: number
				},
				event: PointerEvent
			) => {
				local.current = current.current.value
				if (event.target !== root.current) return
				const x = (state.xy[0] - state.left) / (state.right - state.left)
				const y = (state.bottom - state.xy[1]) / (state.bottom - state.top)
				local.current = setHSVAChannel(
					local.current,
					current.current.axes[0],
					x
				)
				local.current = setHSVAChannel(
					local.current,
					current.current.axes[1],
					y
				)
				current.current.onChange?.(local.current)
			},
			onDrag: (state: {
				xy: readonly [number, number]
				initial: readonly [number, number]
				width: number
				height: number
			}) => {
				let next = tweakHSVAChannel(
					local.current,
					current.current.axes[0],
					(state.xy[0] - state.initial[0]) / state.width
				)
				next = tweakHSVAChannel(
					next,
					current.current.axes[1],
					(state.initial[1] - state.xy[1]) / state.height
				)
				current.current.onChange?.(next)
			},
		}),
		[disabled]
	)
	const drag = useDrag(root, dragOptions)
	const uniforms = useMemo(() => {
		const {h, s, v, a} = value
		return {hsva: [h, s, v, a], axes: axes.map(colorChannelToIndex)}
	}, [axes, value])
	const x = getHSVAChannel(value, axes[0])
	const y = getHSVAChannel(value, axes[1])
	const tweakingInside =
		drag.dragging &&
		drag.left <= drag.xy[0] &&
		drag.right >= drag.xy[0] &&
		drag.top <= drag.xy[1] &&
		drag.bottom >= drag.xy[1]

	return (
		<div
			ref={root}
			data-tq-component="input-color-channel-pad"
			data-tq-part="root"
			style={{cursor: tweakingInside ? 'none' : undefined}}
		>
			<GlslCanvas
				data-tq-part="canvas"
				fragmentString={PadFragmentString}
				uniforms={uniforms}
			/>
			<div
				data-tq-part="handle"
				data-tq-tweaking={drag.dragging ? '' : undefined}
				style={
					{
						left: toPercent(x),
						bottom: toPercent(y),
						background: hsva2hex({...value, a: 1}),
					} as CSSProperties
				}
			/>
		</div>
	)
}
