// apps/docs/pages/DemoComponent.tsx
import {Icon, InputComplex, type Scheme, useKeys} from '@tweeq/react'
import {type ReactNode, useState} from 'react'

import {DemoContainer} from './DemoContainer'

export interface DemoListeners {
	update: (value: unknown, ...args: unknown[]) => void
	focus: (...args: unknown[]) => void
	blur: (...args: unknown[]) => void
	confirm: (...args: unknown[]) => void
}

export interface DemoComponentProps<
	V,
	T extends Record<string, unknown>,
> {
	name: string
	initialValue?: V
	scheme: Scheme<T>
	options: T
	children: (props: {
		modelValue: V
		options: T
		listeners: DemoListeners
	}) => ReactNode
}

const MODIFIER_KEYS = ['Meta', 'Shift', 'Alt', 'Control', 'q', 'a', 'r'] as const

function PressedKeys() {
	const keys = useKeys(MODIFIER_KEYS)
	const pressed = MODIFIER_KEYS.filter(key => keys[key])
	if (!pressed.length) return null
	return (
		<div className="pressed-keys">
			{pressed.map(key => (
				<div key={key}>
					{key === 'Meta' ? (
						<Icon icon="material-symbols:keyboard-command-key" />
					) : key === 'Shift' ? (
						<Icon icon="material-symbols:shift-outline" />
					) : key === 'Alt' ? (
						<Icon icon="material-symbols:keyboard-option-key" />
					) : (
						<span>{key.toUpperCase()}</span>
					)}
				</div>
			))}
		</div>
	)
}

/**
 * Port of docs/.vuepress/DemoComponent.vue: the per-component demo on the
 * Components page. Left: the component sandbox (Full Screen capable, with a
 * pressed-keys display while fullscreen). Right: an InputComplex editing the
 * component's props live. Event listeners log to the console like the
 * original, so behaviors can be inspected.
 */
export function DemoComponent<V, T extends Record<string, unknown>>({
	name,
	initialValue,
	scheme,
	options: initialOptions,
	children,
}: DemoComponentProps<V, T>) {
	const [modelValue, setModelValue] = useState(initialValue as V)
	const [options, setOptions] = useState(initialOptions)

	const listeners: DemoListeners = {
		update: (value, ...args) => {
			// eslint-disable-next-line no-console
			console.info(`[${name}] update\t`, value, ...args)
			setModelValue(value as V)
		},
		// eslint-disable-next-line no-console
		focus: (...args) => console.info(`[${name}] focus\t`, ...args),
		// eslint-disable-next-line no-console
		blur: (...args) => console.info(`[${name}] blur\t`, ...args),
		// eslint-disable-next-line no-console
		confirm: (...args) => console.info(`[${name}] confirm\t`, ...args),
	}

	return (
		<DemoContainer className="DemoComponent">
			{({isFullscreen}) => (
				<>
					<div
						className={'input-wrapper' + (isFullscreen ? ' fullscreen' : '')}
					>
						<div className="input">
							{children({modelValue, options, listeners})}
						</div>
						{isFullscreen && <PressedKeys />}
					</div>
					{!isFullscreen && (
						<div className="options">
							{Object.keys(scheme).length > 0 && (
								<InputComplex
									value={options}
									scheme={scheme}
									onChange={setOptions}
								/>
							)}
						</div>
					)}
				</>
			)}
		</DemoContainer>
	)
}

// docs/.vuepress/DemoComponent.vue
<script setup lang="ts" generic="T extends Record<string, unknown>">
import {useMagicKeys} from '@vueuse/core'
import {cloneDeep} from 'lodash-es'
import {Icon, InputComplex} from '@tweeq/vue'
import {ref, shallowRef} from 'vue'

import DemoContainer from './DemoContainer.vue'

interface Props {
	name: string
	initialValue?: any
	scheme: any
	options: T
}

const props = defineProps<Props>()

const options = shallowRef<T>(cloneDeep(props.options))

const modelValue = ref(props.initialValue)

const listeners = {
	update: (value: any, ...args: any[]) => {
		// eslint-disable-next-line no-console
		console.info(`[${props.name}] update\t`, value, ...args)
		modelValue.value = value
	},
	focus: (...args: any[]) => {
		// eslint-disable-next-line no-console
		console.info(`[${props.name}] focus\t`, ...args)
	},
	blur: (...args: any[]) => {
		// eslint-disable-next-line no-console
		console.info(`[${props.name}] blur\t`, ...args)
	},
	confirm: (...args: any[]) => {
		// eslint-disable-next-line no-console
		console.info(`[${props.name}] confirm\t`, ...args)
	},
}

const {current} = useMagicKeys()
</script>

<template>
	<DemoContainer class="DemoComponent">
		<template #default="{isFullscreen}">
			<div class="input-wrapper" :class="{fullscreen: isFullscreen}">
				<div class="input">
					<slot
						:modelValue="modelValue"
						:options="options"
						:listeners="listeners"
					/>
				</div>
				<div v-if="isFullscreen" class="pressed-keys">
					<div v-for="key in current" :key="key">
						<Icon
							v-if="key === 'meta'"
							icon="material-symbols:keyboard-command-key"
						/>
						<Icon
							v-else-if="key === 'shift'"
							icon="material-symbols:shift-outline"
						/>
						<Icon
							v-else-if="key === 'alt'"
							icon="material-symbols:keyboard-option-key"
						/>
						<span v-else>{{ key.toUpperCase() }}</span>
					</div>
				</div>
			</div>

			<div v-if="!isFullscreen" class="options">
				<InputComplex v-model="options" :scheme="scheme" />
			</div>
		</template>
	</DemoContainer>
</template>

<style lang="stylus" scoped>
.DemoComponent
	display grid
	grid-template-columns min-content 1fr

.input-wrapper
	width 15rem

	&.fullscreen
		position relative
		width 640px
		height 480px
		display flex
		flex-direction column
		justify-content center
		align-items center
		outline 1px solid var(--tq-color-border)

.input
	min-width 15em

.pressed-keys
	position absolute
	bottom 2em
	display flex
	box-sizing border-box
	gap .5em
	font-family var(--tq-font-code)

	div
		height 36px
		font-size 24px
		font-size 24px
		background-color var(--tq-color-text-subtle)
		color var(--tq-color-background)
		border-radius var(--tq-radius-popup)
		padding 0 .4em 3px
		text-box trim-both cap alphabetic
		display flex
		align-items center

		span, svg
			display block
			vertical-align middle


			margin-top 3px


.options
	border-left 1px solid black
	margin-left 2rem
	padding-left 2rem
</style>
