// apps/docs/pages/DemoContainer.tsx
import {InputButton, Viewport} from '@tweeq/react'
import {type ReactNode, useState} from 'react'

export interface DemoContainerProps {
	className?: string
	fullscreenEnabled?: boolean
	children: (props: {isFullscreen: boolean}) => ReactNode
}

/**
 * Port of docs/.vuepress/DemoContainer.vue: a tweeq Viewport island inside
 * the VuePress page, with a subtle Full Screen toggle at the top-right.
 * Like the original, ONLY this subtree gets tweeq's base styles.
 */
export function DemoContainer({
	className,
	fullscreenEnabled = true,
	children,
}: DemoContainerProps) {
	const [isFullscreen, setIsFullscreen] = useState(false)

	return (
		<Viewport
			appId="react-demo"
			className={
				'DemoContainer' +
				(isFullscreen ? ' fullscreen' : '') +
				(className ? ` ${className}` : '')
			}
		>
			{fullscreenEnabled && (
				<InputButton
					className="full-screen-button"
					icon={isFullscreen ? 'mdi:fullscreen-exit' : 'mdi:fullscreen'}
					label={isFullscreen ? 'Exit Full Screen' : 'Full Screen'}
					subtle
					onClick={() => setIsFullscreen(fullscreen => !fullscreen)}
				/>
			)}
			{children({isFullscreen})}
		</Viewport>
	)
}

// docs/.vuepress/DemoContainer.vue
<script setup lang="ts">
import * as Tq from '@tweeq/vue'
import {ref} from 'vue'

withDefaults(
	defineProps<{
		fullscreenEnabled: boolean
	}>(),
	{
		fullscreenEnabled: true,
	}
)

defineSlots<{
	default: (props: {isFullscreen: boolean}) => any
}>()

const isFullscreen = ref(false)

function fullScreen() {
	isFullscreen.value = !isFullscreen.value
}
</script>

<template>
	<Tq.Viewport class="DemoContainer" :class="{fullscreen: isFullscreen}">
		<ClientOnly>
			<InputButton
				v-if="fullscreenEnabled"
				class="full-screen-button"
				:icon="isFullscreen ? 'mdi:fullscreen-exit' : 'mdi:fullscreen'"
				:label="isFullscreen ? 'Exit Full Screen' : 'Full Screen'"
				subtle
				@click="fullScreen"
			/>
			<slot :isFullscreen="isFullscreen" />
		</ClientOnly>
	</Tq.Viewport>
</template>

<style lang="stylus" scoped>
.DemoContainer
	--demo-margin 1rem
	position relative
	padding calc(var(--demo-margin) * 2 + var(--tq-input-height)) 0 2rem

	&.fullscreen
		position fixed
		display flex
		flex-direction column
		justify-content center
		align-items center
		z-index 1000
		inset 0
		background-color var(--tq-color-background)

.full-screen-button
	position absolute !important
	top var(--demo-margin)
	right 0rem

	.fullscreen &
		top 2rem
		right 2rem
</style>
