// packages/vue/src/InputCheckbox/InputCheckbox.vue
<script lang="ts" setup>
import {uniqueId} from 'lodash-es'
import {ref, useTemplateRef} from 'vue'

import Icon from '../Icon/Icon.vue'
import InputSwitchOverlay from '../InputSwitch/InputSwitchOverlay.vue'
import {useInputSwitch} from '../InputSwitch/utils'
import {InputEmits} from '../types'
import {InputCheckboxProps} from './types'

const model = defineModel<boolean>({required: true})

const props = defineProps<InputCheckboxProps>()

const emit = defineEmits<InputEmits>()

const id = ref(uniqueId('InputCheckbox_'))

const track = useTemplateRef('track')
const input = useTemplateRef('input')

const {tweakingValue, subfocus} = useInputSwitch({
	track,
	input,
	props,
	emit,
})
</script>

<template>
	<div
		class="TqInputCheckbox"
		:class="{disabled: props.disabled}"
		:aria-invalid="props.invalid || undefined"
		data-tq-component="input-checkbox"
		:data-disabled="props.disabled || undefined"
		data-tq-part="root"
	>
		<div
			ref="track"
			class="checkbox"
			:class="{subfocus}"
			:block-position="props.blockPosition"
			:inline-position="props.inlinePosition"
			:data-subfocus="subfocus || undefined"
			data-tq-part="track"
		>
			<input
				:id="id"
				ref="input"
				:checked="model"
				:disabled="props.disabled"
				class="input"
				data-tq-part="input"
				type="checkbox"
			/>
			<span class="mark" data-tq-part="mark">
				<Icon :icon="props.icon || 'mdi:check-bold'" />
			</span>
			<InputSwitchOverlay :modelValue="tweakingValue" />
		</div>
		<label v-if="label" :for="id" data-tq-part="label">
			{{ label }}
		</label>
	</div>
</template>

// packages/react/src/components/InputCheckbox/InputCheckbox.tsx
import type {InputBoxProps, InputEvents} from '@tweeq/core'
import {type HTMLAttributes, useId, useRef} from 'react'

import {Icon} from '../Icon'
import {InputSwitchOverlay, useInputSwitch} from '../InputSwitch'

export interface InputCheckboxProps
	extends InputBoxProps,
		InputEvents,
		Omit<HTMLAttributes<HTMLDivElement>, 'onBlur' | 'onChange' | 'onFocus'> {
	value: boolean
	onChange?: (value: boolean) => void
	label?: string
	icon?: string
}

export function InputCheckbox({
	value,
	onChange,
	label,
	icon,
	disabled,
	invalid,
	inlinePosition,
	blockPosition,
	onFocus,
	onBlur,
	onConfirm,
	className,
	...props
}: InputCheckboxProps) {
	const id = useId()
	const track = useRef<HTMLDivElement>(null)
	const input = useRef<HTMLInputElement>(null)
	const controls = useInputSwitch({
		track,
		input,
		value,
		onChange,
		disabled,
		onFocus,
		onBlur,
		onConfirm,
	})

	return (
		<div
			{...props}
			className={className}
			aria-invalid={invalid || undefined}
			data-tq-component="input-checkbox"
			data-disabled={disabled || undefined}
			data-tq-part="root"
		>
			<div
				ref={track}
				block-position={blockPosition}
				inline-position={inlinePosition}
				data-subfocus={controls.subfocus || undefined}
				data-tq-part="track"
			>
				<input
					id={id}
					ref={input}
					checked={value}
					disabled={disabled}
					data-tq-part="input"
					type="checkbox"
					onChange={controls.onChangeInput}
					onKeyDown={controls.onKeyDown}
					onFocus={controls.onFocusInput}
					onBlur={controls.onBlurInput}
				/>
				<span data-tq-part="mark">
					<Icon icon={icon || 'mdi:check-bold'} />
				</span>
				<InputSwitchOverlay value={controls.tweakingValue} />
			</div>
			{label && <label htmlFor={id} data-tq-part="label">{label}</label>}
		</div>
	)
}
