// packages/react/src/components/InputCubicBezier/InputCubicBezierPicker.tsx
import {
	type CubicBezierValue,
	getCubicBezierPath,
	updateCubicBezierPoint,
} from '@tweeq/core'
import {type HTMLAttributes, useMemo, useRef} from 'react'

import {useDrag} from '../../hooks'

export interface InputCubicBezierPickerProps
	extends Omit<HTMLAttributes<HTMLDivElement>, 'onChange'> {
	value: CubicBezierValue
	onChange?: (value: CubicBezierValue) => void
	onConfirm?: () => void
	disabled?: boolean
}

export function InputCubicBezierPicker({
	value,
	onChange,
	onConfirm,
	disabled,
	className,
	...props
}: InputCubicBezierPickerProps) {
	const editor = useRef<SVGSVGElement>(null)
	const draggingPoint = useRef<0 | 1 | null>(null)
	const callbacks = useRef({value, onChange, onConfirm})
	callbacks.current = {value, onChange, onConfirm}
	const dragOptions = useMemo(
		() => ({
			disabled: () => Boolean(disabled),
			dragDelaySeconds: 0,
			onDrag: ({
				xy,
				left,
				right,
				top,
				bottom,
			}: {
				xy: readonly [number, number]
				left: number
				right: number
				top: number
				bottom: number
			}) => {
				const point = draggingPoint.current
				if (point === null) return
				const x = (xy[0] - left) / (right - left)
				const y = (bottom - xy[1]) / (bottom - top)
				callbacks.current.onChange?.(
					updateCubicBezierPoint(callbacks.current.value, point, x, y)
				)
			},
			onDragEnd: () => {
				draggingPoint.current = null
				callbacks.current.onConfirm?.()
			},
		}),
		[disabled]
	)
	useDrag(editor, dragOptions)
	const [x1, y1, x2, y2] = value

	return (
		<div
			{...props}
			className={className}
			data-tq-component="input-cubic-bezier-picker"
			data-tq-part="picker"
		>
			<svg
				ref={editor}
				viewBox="0 0 1 1"
				data-tq-part="pad"
			>
				<g>
					<line x1={0} y1={0} x2={x1} y2={y1} />
					<line x1={1} y1={1} x2={x2} y2={y2} />
					<path d={getCubicBezierPath(value)} />
					<circle
						cx={x1}
						cy={y1}
						r=".035"
						onPointerDown={() => (draggingPoint.current = 0)}
						data-tq-part="handle-0"
					/>
					<circle
						cx={x2}
						cy={y2}
						r=".035"
						onPointerDown={() => (draggingPoint.current = 1)}
						data-tq-part="handle-1"
					/>
				</g>
			</svg>
		</div>
	)
}

// packages/vue/src/InputCubicBezier/InputCubicBezierPicker.vue
<script lang="ts" setup>
import {
	getCubicBezierPath,
	updateCubicBezierPoint,
	type CubicBezierValue,
} from '@tweeq/core'
import {vec2} from 'linearly'
import {computed, ref, useTemplateRef} from 'vue'

import {useDrag} from '../use/useDrag'
import type {InputCubicBezierProps} from './types'

const props = defineProps<InputCubicBezierProps>()

const emit = defineEmits<{
	'update:modelValue': [CubicBezierValue]
	confirm: []
}>()

const $editor = useTemplateRef('$editor')

useDrag($editor, {
	disabled: computed(() => props.disabled),
	dragDelaySeconds: 0,
	onDrag({xy, left, right, top, bottom}) {
		if (draggingPoint.value === null) return

		const uv = vec2.invlerp([left, bottom], [right, top], xy)
		const [x, y] = vec2.clamp(uv, [0, 0], [1, 1])

		emit(
			'update:modelValue',
			updateCubicBezierPoint(
				props.modelValue,
				draggingPoint.value as 0 | 1,
				x,
				y
			)
		)
	},
	onDragEnd() {
		draggingPoint.value = null
		emit('confirm')
	},
})

const easingPath = computed(() => getCubicBezierPath(props.modelValue))

const x1 = computed(() => props.modelValue[0])
const y1 = computed(() => props.modelValue[1])
const x2 = computed(() => props.modelValue[2])
const y2 = computed(() => props.modelValue[3])

const draggingPoint = ref<number | null>(null)
</script>

<template>
	<div
		class="InputCubicBezierPicker"
		data-tq-component="input-cubic-bezier-picker"
		data-tq-part="picker"
	>
		<svg ref="$editor" viewBox="0 0 1 1" class="pad" data-tq-part="pad">
			<g>
				<line :x1="0" :y1="0" :x2="x1" :y2="y1" />
				<line :x1="1" :y1="1" :x2="x2" :y2="y2" />
				<path :d="easingPath" />
				<circle
					:cx="x1"
					:cy="y1"
					r=".035"
					data-tq-part="handle-0"
					@pointerdown="draggingPoint = 0"
				/>
				<circle
					:cx="x2"
					:cy="y2"
					r=".035"
					data-tq-part="handle-1"
					@pointerdown="draggingPoint = 1"
				/>
			</g>
		</svg>
	</div>
</template>
