// packages/vue/src/Tabs/Tabs.vue
<script setup lang="ts">
import {moveTabSelection, resolveActiveTabId} from '@tweeq/core'
import {provide, reactive, watch} from 'vue'

import {useAppConfigStore} from '../stores/appConfig'
import {AddTabKey, DeleteTabKey, TabsProviderKey, UpdateTabKey} from './symbols'
import type {Tab, TabsProps, TabsState} from './types'

const props = defineProps<TabsProps>()

const emit = defineEmits<{
	changed: [tab: Tab]
	clicked: [tab: Tab]
}>()

const state: TabsState = reactive({
	activeId: '',
	tabs: [] as Tab[],
})

provide(TabsProviderKey, state)

provide(AddTabKey, tab => {
	if (!state.tabs.some(item => item.id === tab.id)) state.tabs.push(tab)
})

provide(UpdateTabKey, (id: string, data: Tab) => {
	const tabIndex = state.tabs.findIndex(tab => tab.id === id)
	if (tabIndex < 0) return

	data.isActive = state.tabs[tabIndex].isActive
	state.tabs[tabIndex] = data
})

provide(DeleteTabKey, id => {
	const tabIndex = state.tabs.findIndex(tab => tab.id === id)

	state.tabs.splice(tabIndex, 1)
})

const appConfig = useAppConfigStore()
const activeId = appConfig.ref<null | string>(
	props.options?.storageKey ?? `${props.name}.active`,
	null
)

const selectTab = (id: string, event?: Event): void => {
	const selectedTab = findTab(id)

	if (!selectedTab) {
		return
	}

	if (selectedTab.isDisabled) {
		event?.preventDefault()
		return
	}

	if (state.activeId === selectedTab.id) {
		emit('clicked', selectedTab)
		return
	}

	state.tabs.forEach(tab => {
		tab.isActive = tab.id === selectedTab.id
	})

	emit('changed', selectedTab)

	state.activeId = selectedTab.id

	activeId.value = selectedTab.id
}

const findTab = (id: string): Tab | undefined => {
	return state.tabs.find(tab => tab.id === id)
}

function onTabKeydown(event: KeyboardEvent, id: string) {
	const next = moveTabSelection({
		tabs: state.tabs,
		currentId: id,
		key: event.key,
		vertical: Boolean(props.vertical),
	})
	if (!next) return
	event.preventDefault()
	const buttons = (event.currentTarget as HTMLElement)
		.closest('[role="tablist"]')
		?.querySelectorAll<HTMLButtonElement>('[role="tab"]')
	const target = [...(buttons ?? [])].find(
		button => button.dataset.tqTabId === next
	)
	target?.focus()
	if (next !== state.activeId) selectTab(next)
}

// Keep exactly one valid tab active. Reactive (not a one-shot onMounted) because
// tabs register via their own onBeforeMount — which, for tabs rendered by a
// v-for, can land after this parent mounts — and the active tab can later be
// removed. A one-shot check that ran before any tab existed would leave nothing
// selected. Preference: the persisted tab, then an explicit default, then tab 0.
function ensureActiveTab() {
	if (!state.tabs.length) return
	const next = resolveActiveTabId(
		state.tabs,
		state.activeId,
		activeId.value,
		props.options?.defaultTabId
	)
	if (next && next !== state.activeId) selectTab(next)
	else if (!next && state.activeId) {
		state.activeId = ''
		state.tabs.forEach(tab => (tab.isActive = false))
	}
}

watch(
	() => state.tabs.map(tab => `${tab.id}:${tab.isDisabled}`),
	ensureActiveTab,
	{immediate: true}
)
</script>

<template>
	<div
		class="TqTabs"
		:class="{vertical}"
		data-tq-component="tabs"
		:data-tq-orientation="vertical ? 'vertical' : 'horizontal'"
		data-tq-part="root"
	>
		<div class="tablist-wrapper" data-tq-part="tablist-wrapper">
			<div
				v-if="$slots['before-tablist']"
				class="before-tablist"
				data-tq-part="before-tablist"
			>
				<slot name="before-tablist" />
			</div>
			<ul
				role="tablist"
				:aria-orientation="vertical ? 'vertical' : 'horizontal'"
				class="tablist"
				data-tq-part="tablist"
			>
				<li
					v-for="(tab, i) in state.tabs"
					:key="i"
					class="tablist-item"
					:class="{disabled: tab.isDisabled, active: tab.isActive}"
					role="presentation"
					data-tq-part="tablist-item"
					:data-tq-disabled="tab.isDisabled ? '' : undefined"
					:data-tq-active="tab.isActive ? '' : undefined"
				>
					<button
						:id="tab.tabId"
						type="button"
						class="tablist-link"
						:class="{disabled: tab.isDisabled, active: tab.isActive}"
						role="tab"
						:aria-controls="tab.paneId"
						:aria-selected="tab.isActive"
						:disabled="tab.isDisabled"
						:tabindex="tab.isActive ? 0 : -1"
						data-tq-tab=""
						:data-tq-tab-id="tab.id"
						:data-tq-part="`tab-${tab.id}`"
						@click="selectTab(tab.id, $event)"
						@keydown="onTabKeydown($event, tab.id)"
						>{{ tab.name }}</button
					>
				</li>
			</ul>
		</div>
		<div class="panels-wrapper" data-tq-part="panels-wrapper">
			<slot />
		</div>
	</div>
</template>
../stores/useAppStorage

// packages/react/src/components/Tabs/Tabs.tsx
import {moveTabSelection, resolveActiveTabId} from '@tweeq/core'
import {
	type HTMLAttributes,
	type KeyboardEvent,
	type ReactNode,
	useCallback,
	useEffect,
	useMemo,
	useState,
} from 'react'

import {classNames} from '../../classNames'
import {useConfigRef} from '../../hooks'
import {useTweeqRuntime} from '../../runtime'
import {type TabRegistration, TabsContext} from './TabsContext'

export interface TabsProps extends HTMLAttributes<HTMLDivElement> {
	name: string
	vertical?: boolean
	options?: {storageKey?: string; defaultTabId?: string}
	beforeTablist?: ReactNode
	onChanged?: (tab: TabRegistration) => void
	onClicked?: (tab: TabRegistration) => void
}

export function Tabs({
	name,
	vertical = false,
	options,
	beforeTablist,
	onChanged,
	onClicked,
	children,
	className,
	...props
}: TabsProps) {
	const {appConfigStore} = useTweeqRuntime()
	const entry = useMemo(
		() =>
			appConfigStore
				.getState()
				.ref<string | null>(options?.storageKey ?? `${name}.active`, null),
		[appConfigStore, name, options?.storageKey]
	)
	const [persistedId, setPersistedId] = useConfigRef(entry)
	const [tabs, setTabs] = useState<TabRegistration[]>([])
	const [activeId, setActiveId] = useState('')
	const register = useCallback((tab: TabRegistration) => {
		setTabs(current =>
			current.some(item => item.id === tab.id) ? current : [...current, tab]
		)
		return () => setTabs(current => current.filter(item => item.id !== tab.id))
	}, [])
	const update = useCallback((tab: TabRegistration) => {
		setTabs(current => current.map(item => (item.id === tab.id ? tab : item)))
	}, [])

	const select = useCallback(
		(id: string, event?: {preventDefault(): void}) => {
			const selected = tabs.find(tab => tab.id === id)
			if (!selected) return
			if (selected.isDisabled) {
				event?.preventDefault()
				return
			}
			if (activeId === selected.id) {
				onClicked?.(selected)
				return
			}
			setActiveId(selected.id)
			setPersistedId(selected.id)
			onChanged?.(selected)
		},
		[activeId, onChanged, onClicked, setPersistedId, tabs]
	)

	const onTabKeyDown = useCallback(
		(event: KeyboardEvent<HTMLButtonElement>, id: string) => {
			const next = moveTabSelection({
				tabs,
				currentId: id,
				key: event.key,
				vertical,
			})
			if (!next) return
			event.preventDefault()
			const buttons = event.currentTarget
				.closest('[role="tablist"]')
				?.querySelectorAll<HTMLButtonElement>('[role="tab"]')
			const target = [...(buttons ?? [])].find(
				button => button.dataset.tqTabId === next
			)
			target?.focus()
			if (next !== activeId) select(next)
		},
		[activeId, select, tabs, vertical]
	)

	useEffect(() => {
		if (!tabs.length) return
		const next = resolveActiveTabId(
			tabs,
			activeId,
			persistedId,
			options?.defaultTabId
		)
		if (next && next !== activeId) select(next)
		else if (!next && activeId) setActiveId('')
	}, [activeId, options?.defaultTabId, persistedId, select, tabs])

	const context = useMemo(
		() => ({activeId, register, update}),
		[activeId, register, update]
	)

	return (
		<TabsContext.Provider value={context}>
			<div
				{...props}
				className={classNames('TqTabs', className)}
				data-tq-component="tabs"
				data-tq-orientation={vertical ? 'vertical' : 'horizontal'}
				data-tq-part="root"
			>
				<div data-tq-part="tablist-wrapper">
					{beforeTablist && <div data-tq-part="before-tablist">{beforeTablist}</div>}
					<ul
						role="tablist"
						aria-orientation={vertical ? 'vertical' : 'horizontal'}
						data-tq-part="tablist"
					>
						{tabs.map(tab => (
							<li
								key={tab.id}
								role="presentation"
								data-tq-part="tablist-item"
								data-tq-disabled={tab.isDisabled ? '' : undefined}
								data-tq-active={tab.id === activeId ? '' : undefined}
							>
								<button
									id={tab.tabId}
									type="button"
									role="tab"
									aria-controls={tab.paneId}
									aria-selected={tab.id === activeId}
									disabled={tab.isDisabled}
									tabIndex={tab.id === activeId ? 0 : -1}
									data-tq-tab=""
									data-tq-tab-id={tab.id}
									data-tq-part={`tab-${tab.id}`}
									onClick={event => select(tab.id, event)}
									onKeyDown={event => onTabKeyDown(event, tab.id)}
								>
									{tab.name}
								</button>
							</li>
						))}
					</ul>
				</div>
				<div data-tq-part="panels-wrapper">{children}</div>
			</div>
		</TabsContext.Provider>
	)
}
