// packages/react/src/components/TitleBar/TitleBar.tsx
import {decorateActionMenuItems} from '@tweeq/dom'
import {type HTMLAttributes, type ReactNode, useRef, useState} from 'react'
import {useStore} from 'zustand'

import {useTweeqRuntime} from '../../runtime'
import {ColorIcon} from '../ColorIcon'
import {Menu} from '../Menu'
import {Popover} from '../Popover'

export interface TitleBarProps extends HTMLAttributes<HTMLDivElement> {
	name: string
	icon: string
	left?: ReactNode
	center?: ReactNode
	right?: ReactNode
}

export function TitleBar({
	name,
	icon,
	left,
	center,
	right,
	className,
	...props
}: TitleBarProps) {
	const {actionsStore} = useTweeqRuntime()
	const appIcon = useRef<HTMLDivElement>(null)
	const menu = useStore(actionsStore, state => state.menu)
	const [menuShown, setMenuShown] = useState(false)
	const [menuAutoFocus, setMenuAutoFocus] = useState(false)
	const [focusWithin, setFocusWithin] = useState(false)
	const closeMenu = () => {
		setMenuShown(false)
		setMenuAutoFocus(false)
		appIcon.current?.focus()
	}

	return (
		<div
			{...props}
			className={className}
			data-tq-component="title-bar"
			data-tq-no-drag={menuShown || focusWithin ? '' : undefined}
			onFocus={() => setFocusWithin(true)}
			data-tq-part="root"
			onBlur={event => {
				if (!event.currentTarget.contains(event.relatedTarget))
					setFocusWithin(false)
			}}
		>
			<div data-tq-part="left">
				<ColorIcon
					ref={appIcon}
					src={icon}
					role="button"
					tabIndex={0}
					aria-label={`${name} menu`}
					aria-expanded={menuShown}
					data-tq-part="menu-trigger"
					onClick={() => {
						setMenuAutoFocus(false)
						setMenuShown(current => !current)
					}}
					onKeyDown={event => {
						if (event.key === 'Enter' || event.key === ' ') {
							event.preventDefault()
							setMenuAutoFocus(true)
							setMenuShown(current => !current)
						}
					}}
				/>
				<Popover
					reference={appIcon.current}
					placement="bottom-start"
					open={menuShown}
					onChangeOpen={open => {
						if (open) setMenuShown(true)
						else closeMenu()
					}}
				>
					<Menu
						items={decorateActionMenuItems(menu)}
						autoFocus={menuAutoFocus}
						onClose={closeMenu}
					/>
				</Popover>
				<span data-tq-part="app-name">{name}</span>
				{left}
			</div>
			<div data-tq-part="center">{center}</div>
			<div data-tq-part="right">{right}</div>
		</div>
	)
}

// packages/vue/src/TitleBar/TitleBar.vue
<script setup lang="ts">
import {decorateActionMenuItems} from '@tweeq/dom'
import {computed, nextTick, ref, useTemplateRef} from 'vue'

import {ColorIcon} from '../ColorIcon'
import {Menu} from '../Menu'
import {Popover} from '../Popover'
import {useActionsStore} from '../stores/actions'
import type {TitleBarProps} from './types'

defineProps<TitleBarProps>()

defineSlots<{
	left(): any
	center(): any
	right(): any
}>()

const actions = useActionsStore()

const appIcon = useTemplateRef<any>('appIcon')
const appMenu = useTemplateRef<any>('appMenu')

const isMenuShown = ref(false)
const menuAutoFocus = ref(false)

// The whole bar is a drag region (-webkit-app-region: drag), and the OS
// swallows pointer events over drag regions — so clicking the bar's background
// never reaches the DOM, and neither a popover's light-dismiss nor an input's
// blur fires. While the app menu is open or something inside the bar is
// focused, turn dragging off so those background clicks register and dismiss.
const hasFocusWithin = ref(false)
const noDrag = computed(() => isMenuShown.value || hasFocusWithin.value)

const menus = computed(() => decorateActionMenuItems(actions.menu))

function onFocusOut(event: FocusEvent) {
	const root = event.currentTarget as HTMLElement
	if (!root.contains(event.relatedTarget as Node | null)) {
		hasFocusWithin.value = false
	}
}

function toggleMenu() {
	menuAutoFocus.value = false
	isMenuShown.value = !isMenuShown.value
}

function onIconKeydown(event: KeyboardEvent) {
	if (event.key !== 'Enter' && event.key !== ' ') return
	event.preventDefault()
	menuAutoFocus.value = true
	isMenuShown.value = !isMenuShown.value
}

function closeMenu() {
	isMenuShown.value = false
	menuAutoFocus.value = false
	void nextTick(() => appIcon.value?.$el?.focus?.() ?? appIcon.value?.focus?.())
}
</script>

<template>
	<div
		class="TqTitleBar"
		:class="{noDrag}"
		data-tq-component="title-bar"
		:data-tq-no-drag="noDrag ? '' : undefined"
		data-tq-part="root"
		@focusin="hasFocusWithin = true"
		@focusout="onFocusOut"
	>
		<div class="left" data-tq-part="left">
			<ColorIcon
				ref="appIcon"
				class="app-icon"
				:src="icon"
				:class="{shown: isMenuShown}"
				role="button"
				tabindex="0"
				:aria-label="`${name} menu`"
				:aria-expanded="isMenuShown"
				data-tq-part="menu-trigger"
				@click="toggleMenu"
				@keydown="onIconKeydown"
			/>
			<Popover
				:reference="appIcon"
				placement="bottom-start"
				v-model:open="isMenuShown"
			>
				<Menu
					v-if="isMenuShown"
					ref="appMenu"
					:items="menus"
					:auto-focus="menuAutoFocus"
					@close="closeMenu"
				/>
			</Popover>
			<span class="app-name" data-tq-part="app-name">{{ name }}</span>
			<slot name="left" />
		</div>
		<div class="center" data-tq-part="center">
			<slot name="center" />
		</div>
		<div class="right" data-tq-part="right">
			<slot name="right" />
		</div>
	</div>
</template>
