// src/react/components/InputSwitch/InputSwitch.tsx
import {type HTMLAttributes, useId, useRef} from 'react'

import {type InputBoxProps, type InputEvents} from '../../../core'
import {classNames} from '../../classNames'
import styles from './InputSwitch.module.styl'
import {useInputSwitch} from './useInputSwitch'

export interface InputSwitchProps
	extends InputBoxProps,
		InputEvents,
		Omit<HTMLAttributes<HTMLDivElement>, 'onBlur' | 'onChange' | 'onFocus'> {
	value: boolean
	onChange?: (value: boolean) => void
	label?: string
}

export function InputSwitch({
	value,
	onChange,
	label,
	disabled,
	invalid,
	onFocus,
	onBlur,
	onConfirm,
	inlinePosition,
	blockPosition,
	className,
	...props
}: InputSwitchProps) {
	const id = useId()
	const track = useRef<HTMLDivElement>(null)
	const input = useRef<HTMLInputElement>(null)
	const controls = useInputSwitch({
		track,
		input,
		value,
		onChange,
		disabled,
		onFocus,
		onBlur,
		onConfirm,
	})

	return (
		<div
			{...props}
			className={classNames(styles.tqInputSwitch, className)}
			aria-invalid={invalid || undefined}
		>
			<div
				ref={track}
				className={classNames(
					styles.track,
					controls.subfocus && styles.subfocus
				)}
				inline-position={inlinePosition}
				block-position={blockPosition}
			>
				<input
					id={id}
					ref={input}
					checked={value}
					disabled={disabled}
					className={styles.input}
					type="checkbox"
					onChange={controls.onChangeInput}
					onKeyDown={controls.onKeyDown}
					onFocus={controls.onFocusInput}
					onBlur={controls.onBlurInput}
				/>
				<div
					className={classNames(
						styles.handle,
						controls.tweakingValue !== null && styles.tweaking
					)}
				/>
			</div>
			{label && <label htmlFor={id}>{label}</label>}
		</div>
	)
}

// packages/vue/src/InputSwitch/InputSwitch.vue
<script lang="ts" setup>
import {uniqueId} from 'lodash-es'
import {ref, useTemplateRef} from 'vue'

import {InputEmits} from '../types'
import {InputSwitchProps} from './types'
import {useInputSwitch} from './utils'

const model = defineModel<boolean>({required: true})

const props = defineProps<InputSwitchProps>()

const emit = defineEmits<InputEmits>()

const id = ref(uniqueId('InputSwitch_'))

const track = useTemplateRef('track')
const input = useTemplateRef('input')

const {tweakingValue, subfocus} = useInputSwitch({
	track,
	input,
	props,
	emit,
})
</script>

<template>
	<div class="TqInputSwitch" data-tq-component="input-switch" data-tq-part="root" :aria-invalid="invalid || undefined">
		<div
			ref="track"
			class="track"
			:class="{subfocus}"
			data-tq-part="track"
			:data-subfocus="subfocus || undefined"
			:inline-position="inlinePosition"
			:block-position="blockPosition"
		>
			<input
				:id="id"
				ref="input"
				:checked="!!model"
				:disabled="disabled"
				class="input"
				data-tq-part="input"
				type="checkbox"
			/>
			<div
				class="handle"
				:class="{tweaking: tweakingValue !== null}"
				:data-tweaking="tweakingValue !== null || undefined"
				data-tq-part="handle"
			/>
		</div>
		<label v-if="label" :for="id" data-tq-part="label">
			{{ label }}
		</label>
	</div>
</template>
