// packages/react/src/components/App/App.tsx
import {type HTMLAttributes, type ReactNode} from 'react'

import {type TweeqOptions} from '../../initTweeq'
import {TweeqProvider} from '../TweeqProvider'
import {Viewport} from '../Viewport'

export interface AppProps
	extends Omit<HTMLAttributes<HTMLDivElement>, 'title'>,
		TweeqOptions {
	appId?: string
	title?: ReactNode
	withProvider?: boolean
	embedded?: boolean
}

export function App({
	appId = 'app',
	title,
	withProvider = true,
	embedded = false,
	children,
	className,
	colorMode,
	accentColor,
	backgroundColor,
	grayColor,
	colorPresets,
	...props
}: AppProps) {
	const content = (
		<Viewport
			{...props}
			className={className}
			appId={appId}
			data-tq-app=""
			data-tq-embedded={embedded ? '' : undefined}
			data-tq-part="root"
		>
			{title}
			<main data-tq-part="main">{children}</main>
		</Viewport>
	)
	if (!withProvider) return content
	return (
		<TweeqProvider
			appId={appId}
			colorMode={colorMode}
			accentColor={accentColor}
			backgroundColor={backgroundColor}
			grayColor={grayColor}
			colorPresets={colorPresets}
		>
			{content}
		</TweeqProvider>
	)
}

// packages/vue/src/App/App.vue
<script setup lang="ts">
import {TweeqProvider} from '../TweeqProvider'
import {Viewport} from '../Viewport'
import type {AppProps} from './types'

const props = withDefaults(defineProps<AppProps>(), {
	appId: 'app',
	withProvider: true,
	embedded: false,
})

defineSlots<{
	title: () => unknown
	default: () => unknown
}>()
</script>

<template>
	<TweeqProvider
		v-if="props.withProvider"
		:app-id="props.appId"
		:color-mode="props.colorMode"
		:accent-color="props.accentColor"
		:background-color="props.backgroundColor"
		:gray-color="props.grayColor"
		:color-presets="props.colorPresets"
	>
		<Viewport
			:app-id="props.appId"
			:initialize="false"
			class="TqApp"
			:class="{embedded: props.embedded}"
			data-tq-app=""
			:data-tq-embedded="props.embedded ? '' : undefined"
			data-tq-part="root"
		>
			<slot name="title" />
			<main class="main" data-tq-part="main"><slot /></main>
		</Viewport>
	</TweeqProvider>
	<Viewport
		v-else
		:app-id="props.appId"
		class="TqApp"
		:class="{embedded: props.embedded}"
		data-tq-app=""
		:data-tq-embedded="props.embedded ? '' : undefined"
		data-tq-part="root"
	>
		<slot name="title" />
		<main class="main" data-tq-part="main"><slot /></main>
	</Viewport>
</template>
