// packages/vue/src/InputCode/InputCode.vue
<script setup lang="ts">
import {MonacoEditor} from '../MonacoEditor'
import type {InputCodeProps} from './types'

defineProps<InputCodeProps>()

defineEmits<{
	'update:modelValue': [string]
}>()
</script>

<template>
	<div class="TqInputCode" data-tq-component="input-code" data-tq-part="root">
		<MonacoEditor
			class="monaco-editor"
			data-tq-part="editor"
			:modelValue="modelValue"
			:lang="lang"
			:errors="errors"
			@update:modelValue="$emit('update:modelValue', $event)"
		/>
	</div>
</template>

// packages/react/src/components/InputCode/InputCode.tsx
import {type HTMLAttributes} from 'react'

import {MonacoEditor, type MonacoEditorProps} from '../MonacoEditor'

export interface InputCodeProps
	extends Omit<HTMLAttributes<HTMLDivElement>, 'onChange'>,
		Pick<MonacoEditorProps, 'errors'> {
	value: string
	onChange?: (value: string) => void
	lang: string
}

export function InputCode({
	value,
	onChange,
	lang,
	errors,
	className,
	...props
}: InputCodeProps) {
	return (
		<div
			{...props}
			className={className}
			data-tq-component="input-code"
			data-tq-part="root"
		>
			<MonacoEditor
				data-tq-part="editor"
				value={value}
				onChange={onChange}
				lang={lang}
				errors={errors}
			/>
		</div>
	)
}
