// packages/react/src/components/Popover/Popover.tsx
import {
	getPopoverGeometry,
	getPopoverPositionStyles,
	type PopoverOffset,
	type PopoverPlacement,
} from '@tweeq/core'
import {addAnchorName} from '@tweeq/dom'
import {type vec2} from 'linearly'
import {
	type CSSProperties,
	type HTMLAttributes,
	useCallback,
	useLayoutEffect,
	useMemo,
	useRef,
	useState,
} from 'react'
import {createPortal} from 'react-dom'

import {useEventListener, useResizeObserver} from '../../hooks'
import {Balloon} from '../Balloon'

let instanceCount = 0

export interface PopoverProps
	extends Omit<HTMLAttributes<HTMLDivElement>, 'onToggle'> {
	reference: HTMLElement | null
	open: boolean
	placement?: PopoverPlacement | vec2
	offset?: PopoverOffset
	lightDismiss?: boolean
	arrow?: boolean
	flash?: boolean
	teleport?: string
	anchorName?: string
	exitTransition?: boolean
	onChangeOpen?: (open: boolean) => void
	onClose?: () => void
}

interface LayoutState {
	shiftX: number
	shiftY: number
	arrowSide?: 'top' | 'bottom' | 'left' | 'right'
	arrowOffset: number
}

const INITIAL_LAYOUT: LayoutState = {
	shiftX: 0,
	shiftY: 0,
	arrowOffset: 0,
}

export function Popover({
	reference,
	open,
	placement = 'bottom-start',
	offset = 0,
	lightDismiss = true,
	arrow = false,
	flash = false,
	teleport,
	anchorName: fixedAnchorName,
	exitTransition = false,
	onChangeOpen,
	onClose,
	className,
	style,
	children,
	...props
}: PopoverProps) {
	const popover = useRef<HTMLDivElement>(null)
	const [generatedAnchorName] = useState(
		() => `--tq-popover-${instanceCount++}`
	)
	const anchorName = fixedAnchorName ?? generatedAnchorName
	const [layout, setLayout] = useState<LayoutState>(INITIAL_LAYOUT)
	const layoutRef = useRef(layout)
	layoutRef.current = layout

	useLayoutEffect(() => {
		if (fixedAnchorName || !reference) return
		return addAnchorName(reference, anchorName)
	}, [anchorName, fixedAnchorName, reference])

	const update = useCallback(
		(resetShift = false) => {
			const element = popover.current
			if (!reference || !element || typeof placement !== 'string') return
			const current = resetShift ? INITIAL_LAYOUT : layoutRef.current
			const next = getPopoverGeometry({
				reference: reference.getBoundingClientRect(),
				popover: element.getBoundingClientRect(),
				placement,
				currentShiftX: current.shiftX,
				currentShiftY: current.shiftY,
				viewportWidth: document.documentElement.clientWidth,
				viewportHeight: document.documentElement.clientHeight,
				arrow,
			})
			layoutRef.current = next
			setLayout(previous =>
				previous.shiftX === next.shiftX &&
				previous.shiftY === next.shiftY &&
				previous.arrowSide === next.arrowSide &&
				previous.arrowOffset === next.arrowOffset
					? previous
					: next
			)
		},
		[arrow, placement, reference]
	)

	useLayoutEffect(() => {
		const element = popover.current
		if (!element) return
		let frame: number | undefined

		try {
			if (open) {
				if (!element.matches(':popover-open')) element.showPopover()
				layoutRef.current = INITIAL_LAYOUT
				setLayout(INITIAL_LAYOUT)
				update(true)
				frame = requestAnimationFrame(() => update())
			} else if (element.matches(':popover-open')) {
				element.hidePopover()
			}
		} catch {
			// Unsupported or already transitioned; content remains in DOM.
		}

		return () => {
			if (frame !== undefined) cancelAnimationFrame(frame)
		}
	}, [open, update])

	useEventListener<ToggleEvent>(popover, 'toggle', event => {
		const isOpen = event.newState === 'open'
		if (!isOpen) onClose?.()
		onChangeOpen?.(isOpen)
	})
	useEventListener(
		typeof document === 'undefined' ? null : document,
		'scroll',
		() => update(),
		{capture: true, passive: true}
	)
	useEventListener(
		typeof window === 'undefined' ? null : window,
		'resize',
		() => update()
	)
	useResizeObserver(popover, () => update())

	const positionStyle = useMemo(
		() => getPopoverPositionStyles(placement, offset, anchorName),
		[anchorName, offset, placement]
	)
	const mergedStyle = {
		...positionStyle,
		...(layout.shiftX || layout.shiftY
			? {transform: `translate(${layout.shiftX}px, ${layout.shiftY}px)`}
			: {}),
		...style,
	} as CSSProperties

	if (!open && !exitTransition) return null

	const content = (
		<div
			{...props}
			ref={popover}
			className={className}
			popover={lightDismiss ? 'auto' : 'manual'}
			style={mergedStyle}
			data-tq-component="popover"
			data-tq-exit-transition={exitTransition ? '' : undefined}
			data-tq-part="root"
		>
			{arrow ? (
				<Balloon
					arrowSide={layout.arrowSide}
					arrowOffset={layout.arrowOffset}
					flash={flash}
				>
					{children}
				</Balloon>
			) : (
				children
			)}
		</div>
	)

	if (!teleport || typeof document === 'undefined') return content
	const target = document.querySelector(teleport)
	return target ? createPortal(content, target) : content
}

// packages/vue/src/Popover/Popover.vue
<script lang="ts" setup>
import {
	getPopoverGeometry,
	getPopoverPositionStyles,
} from '@tweeq/core'
import {addAnchorName} from '@tweeq/dom'
import {unrefElement, useEventListener, useResizeObserver} from '@vueuse/core'
import {computed, ref, useTemplateRef, watch, watchEffect} from 'vue'

import {Balloon} from '../Balloon'
import type {PopoverProps} from './types'

const props = withDefaults(defineProps<PopoverProps>(), {
	open: false,
	placement: 'bottom-start',
	lightDismiss: true,
	offset: 0,
})

const emit = defineEmits<{
	'update:open': [boolean]
	close: []
}>()

const $popover = useTemplateRef<HTMLElement>('$popover')

// CSS anchor name: the caller's fixed one, or a unique generated one. A plain
// counter is enough — this is a client-only app, so there's no SSR hydration to
// keep in sync.
const anchorName = props.anchorName ?? `--tq-popover-${instanceCount++}`

// CSS Anchor Positioning needs the name on the anchor element itself. When we
// generated the name, apply it to the reference ourselves (resolving a possible
// component instance first — TitleBar passes its <ColorIcon>, not a raw
// element) and clean up on change/unmount. When the caller supplied the name,
// they own setting it on the reference.
watchEffect(onCleanup => {
	if (props.anchorName) return
	const el = unrefElement(props.reference)
	if (!el) return
	onCleanup(addAnchorName(el, anchorName))
})

useEventListener($popover, 'toggle', e => {
	const {newState} = e as ToggleEvent
	if (newState === 'closed') {
		emit('close')
	}
	emit('update:open', newState === 'open')
})

watch(
	() => [props.open, $popover.value] as const,
	([open, $popover]) => {
		if (!$popover) return
		try {
			if (
				open &&
				typeof $popover.showPopover === 'function' &&
				!$popover.matches(':popover-open')
			) {
				$popover.showPopover()
			} else if (
				!open &&
				typeof $popover.hidePopover === 'function' &&
				$popover.matches(':popover-open')
			) {
				$popover.hidePopover()
			}
		} catch {
			// Unsupported or already transitioned; content remains in DOM.
		}
		if (open) {
			// Reset the shift so update() re-derives it from the natural position
			// for the new opening (the anchor/reference may have moved).
			shiftX.value = 0
			shiftY.value = 0
			// Resolve the arrow side/offset synchronously (forces a layout read on
			// the just-shown popover) so anything keyed off it — the Balloon's
			// transform-origin, e.g. its pop-in/flash scaling about the arrow — is
			// correct on the very first frame, not a frame late. The rAF pass then
			// settles any post-layout shift.
			update()
			requestAnimationFrame(update)
		}
	}
)

// Derive the Balloon arrow from where the popover actually landed (relative to
// the reference), so it follows flips. Recomputed after it opens and whenever
// the layout shifts.
const arrowSide = ref<'top' | 'bottom' | 'left' | 'right'>()
const arrowOffset = ref(0)

// Cross-axis shift (px) applied via `transform` to slide the popover back into
// the viewport. CSS `position-try-fallbacks` only flips; it never slides a
// centred popover in when the anchor sits near a viewport edge — so we do the
// floating-ui-style "shift" ourselves. Applied as `transform` (not the anchor
// insets), it stays invisible to position-try, so it can't fight the flip.
const shiftX = ref(0)
const shiftY = ref(0)

const shiftStyle = computed<Record<string, string>>(() =>
	shiftX.value || shiftY.value
		? {transform: `translate(${shiftX.value}px, ${shiftY.value}px)`}
		: ({} as Record<string, string>)
)

function update() {
	const reference = unrefElement(props.reference)
	const popover = $popover.value
	// vec2 placements are manual coordinates (e.g. InputDropdown) — leave them be.
	if (!reference || !popover || typeof props.placement !== 'string') return

	const geometry = getPopoverGeometry({
		reference: reference.getBoundingClientRect(),
		popover: popover.getBoundingClientRect(),
		placement: props.placement,
		currentShiftX: shiftX.value,
		currentShiftY: shiftY.value,
		viewportWidth: document.documentElement.clientWidth,
		viewportHeight: document.documentElement.clientHeight,
		arrow: props.arrow,
	})
	shiftX.value = geometry.shiftX
	shiftY.value = geometry.shiftY
	arrowSide.value = geometry.arrowSide
	arrowOffset.value = geometry.arrowOffset
}

// A shared tooltip popover keeps the same instance but swaps its reference, so
// recompute when the reference changes too.
watch(
	() => props.reference,
	() => {
		if (props.open) requestAnimationFrame(update)
	}
)

useEventListener('scroll', update, {capture: true, passive: true})
useEventListener('resize', update)
useResizeObserver($popover, update)

// Map the placement (a floating-ui-style string, or a manual vec2) to inline
// styles. String placements use CSS Anchor Positioning: pin the facing edge to
// the opposite anchor edge via anchor(), align on the cross axis, and let
// position-try-fallbacks flip it into view. vec2 stays a plain fixed coordinate
// (e.g. InputDropdown overlaying the selected option on its input) and never
// touches anchoring.
const styles = computed<Record<string, string>>(() =>
	getPopoverPositionStyles(props.placement, props.offset, anchorName)
)
</script>

<script lang="ts">
let instanceCount = 0
</script>

<template>
	<Teleport :to="teleport" :disabled="!teleport">
		<div
			v-if="open || exitTransition"
			ref="$popover"
			class="Popover"
			:class="{'animate-exit': exitTransition}"
			:style="[styles, shiftStyle]"
			:popover="lightDismiss ? 'auto' : 'manual'"
			data-tq-component="popover"
			:data-tq-exit-transition="exitTransition ? '' : undefined"
			data-tq-part="root"
		>
			<Balloon
				v-if="arrow"
				:arrow-side="arrowSide"
				:arrow-offset="arrowOffset"
				:flash="flash"
			>
				<slot />
			</Balloon>
			<slot v-else />
		</div>
	</Teleport>
</template>
