// packages/react/src/components/InputString/InputString.tsx
import {
	compileStringExpression,
	type InputAlign,
	type InputBoxProps,
	type InputEvents,
	type InputFont,
	type InputTheme,
	type Validator,
	validator as validators,
} from '@tweeq/core'
import {
	forwardRef,
	type HTMLAttributes,
	useImperativeHandle,
	useLayoutEffect,
	useRef,
	useState,
} from 'react'

import {useMultiSelect, useValidator} from '../../hooks'
import {InputTextBase, type InputTextBaseHandle} from '../InputTextBase'

export interface InputStringProps
	extends InputBoxProps,
		InputEvents,
		Omit<
			HTMLAttributes<HTMLDivElement>,
			'default' | 'onBlur' | 'onChange' | 'onFocus'
		> {
	value: string
	onChange?: (value: string) => void
	theme?: InputTheme
	font?: InputFont
	align?: InputAlign
	validator?: Validator<string>
	default?: string
}

export interface InputStringHandle {
	select(): void
	blur(): void
}

export const InputString = forwardRef<InputStringHandle, InputStringProps>(
	function InputStringComponent(
		{
			value,
			onChange,
			theme,
			font,
			align,
			validator = validators.identity,
			default: defaultValue,
			disabled,
			invalid: invalidProp,
			inlinePosition,
			blockPosition,
			onFocus,
			onBlur,
			onConfirm,
			...props
		},
		forwardedRef
	) {
		const [local, setLocal] = useState(value)
		const [display, setDisplay] = useState(value)
		const [focused, setFocused] = useState(false)
		const [expressionEnabled, setExpressionEnabled] = useState(false)
		const [expressionError, setExpressionError] = useState<string>()
		const base = useRef<InputTextBaseHandle>(null)
		const valueRef = useRef(value)
		valueRef.current = value
		const localRef = useRef(local)
		localRef.current = local
		const focusedRef = useRef(focused)
		focusedRef.current = focused
		const validatorRef = useRef(validator)
		validatorRef.current = validator
		const callbacksRef = useRef({onChange, onConfirm})
		callbacksRef.current = {onChange, onConfirm}
		const localAtFocus = useRef('')
		const lastExternalValue = useRef(value)
		const {validateResult} = useValidator(local, validator)

		useLayoutEffect(() => {
			if (Object.is(lastExternalValue.current, value)) return
			lastExternalValue.current = value
			setLocal(value)
			if (!focusedRef.current) setDisplay(value)
		}, [value])

		const applyLocal = (next: string, updateDisplay: boolean) => {
			setLocal(next)
			localRef.current = next
			if (updateDisplay) setDisplay(next)
			const result = validatorRef.current(next)
			if (result.value !== undefined && result.value !== valueRef.current) {
				callbacksRef.current.onChange?.(result.value)
			}
		}

		const multi = useMultiSelect({
			type: 'string',
			getElement: () => base.current?.getRoot() ?? null,
			getValue: () => localRef.current,
			setValue: next => applyLocal(String(next), !focusedRef.current),
			confirm: () => callbacksRef.current.onConfirm?.(),
		})

		const confirm = () => {
			onConfirm?.()
			multi.capture()
			multi.confirm()
			setExpressionEnabled(false)
			setExpressionError(undefined)
			queueMicrotask(() => {
				const current = valueRef.current
				setLocal(current)
				setDisplay(current)
			})
		}

		useImperativeHandle(
			forwardedRef,
			() => ({
				select: () => base.current?.select(),
				blur: () => base.current?.blur(),
			}),
			[]
		)

		return (
			<InputTextBase
				{...props}
				ref={base}
				value={display}
				active={multi.subfocus}
				theme={theme}
				font={font ?? (expressionEnabled ? 'monospace' : undefined)}
				align={align}
				inlinePosition={inlinePosition}
				blockPosition={blockPosition}
				disabled={disabled}
				invalid={
					invalidProp ||
					validateResult.log.length > 0 ||
					Boolean(expressionError)
				}
				default={defaultValue}
				onFocus={() => {
					setFocused(true)
					focusedRef.current = true
					multi.setFocusing(true)
					multi.capture()
					onFocus?.()
				}}
				onBlur={() => {
					confirm()
					setFocused(false)
					focusedRef.current = false
					multi.setFocusing(false)
					onBlur?.()
				}}
				onChange={next => {
					setDisplay(next)
					if (expressionEnabled) {
						try {
							const expression = compileStringExpression(next)
							const result = expression(localAtFocus.current, {i: multi.index})
							applyLocal(result, false)
							setExpressionError(undefined)
							multi.update(expression)
						} catch (error) {
							setExpressionError((error as Error).message)
							multi.update(other => other)
						}
					} else {
						applyLocal(next, false)
						multi.update(() => next)
					}
				}}
				onKeyDown={event => {
					if (event.metaKey && event.key === '=') {
						event.preventDefault()
						setExpressionEnabled(true)
						setDisplay(`"${localRef.current}"`)
						localAtFocus.current = localRef.current
					}
				}}
				onConfirm={confirm}
				onReset={() => {
					if (defaultValue !== undefined) onChange?.(defaultValue)
				}}
			/>
		)
	}
)

// packages/vue/src/InputString/InputString.vue
<script lang="ts" setup>
import {computed, nextTick, ref, useTemplateRef, watch} from 'vue'
import {compileStringExpression} from '@tweeq/core'

import {InputTextBase} from '../InputTextBase'
import {useMultiSelectStore} from '../stores/multiSelect'
import {InputEmits} from '../types'
import {useValidator} from '../use/useValidator'
import * as V from '@tweeq/core/validator'
import {type InputStringProps} from './types'

const model = defineModel<string>({required: true})

const props = withDefaults(defineProps<InputStringProps>(), {
	validator: V.identity,
})

const emit = defineEmits<InputEmits>()

const local = ref(model.value)
const display = ref(model.value)
const {validLocal, validateResult} = useValidator(local, props.validator)

const $input = useTemplateRef('$input')
const focused = ref(false)

const expressionEnabled = ref(false)
const expressionError = ref<string | undefined>(undefined)

const invalid = computed(
	() =>
		props.invalid ||
		validateResult.value.log.length > 0 ||
		!!expressionError.value
)

watch(
	() => model.value,
	value => {
		if (value !== validLocal.value) {
			local.value = value
		}
	},
	{flush: 'sync'}
)

watch(
	() => [local.value, focused.value] as const,
	([local, focusing]) => {
		if (!focusing) {
			display.value = local
		}
	},
	{flush: 'sync'}
)

watch(
	validLocal,
	validLocal => {
		if (validLocal !== undefined && validLocal !== model.value) {
			model.value = validLocal
		}
	},
	{flush: 'sync'}
)

function onFocus() {
	multi.capture()
	emit('focus')
}

function onKeyDown(e: KeyboardEvent) {
	if (e.metaKey && e.key === '=') {
		e.preventDefault()
		enableExpression()
	}
}

let localAtFocus = ''

function enableExpression() {
	expressionEnabled.value = true
	display.value = `"${local.value}"`
	localAtFocus = local.value
}

function onInput(e: Event) {
	const newValue = (e.target as HTMLInputElement).value
	display.value = newValue

	if (expressionEnabled.value) {
		try {
			const fn = compileStringExpression(newValue)
			local.value = fn(localAtFocus, {i: multi.index})
			expressionError.value = undefined
			multi.update(fn)
		} catch (e) {
			expressionError.value = (e as Error).message
			multi.update(x => x)
		}
	} else {
		local.value = newValue
		multi.update(() => newValue)
	}
}

function confirm() {
	emit('confirm')
	multi.capture()
	multi.confirm()

	expressionEnabled.value = false
	expressionError.value = undefined

	nextTick(() => {
		display.value = local.value = model.value
	})
}

function onBlur() {
	confirm()
	emit('blur')
}

defineExpose({
	select: () => {
		$input.value?.select()
	},
	blur: () => {
		$input.value?.blur()
	},
})

//------------------------------------------------------------------------------
// Styles

const font = computed(() => {
	if (props.font) return props.font

	if (expressionEnabled.value) return 'monospace'

	return undefined
})

//------------------------------------------------------------------------------
// Multi Select

const multi = useMultiSelectStore().register({
	type: 'string',
	el: $input,
	focusing: focused,
	getValue: () => local.value,
	setValue(value) {
		local.value = value
	},
	confirm() {
		emit('confirm')
	},
})

function onReset() {
	if (props.default !== undefined) model.value = props.default
}
</script>

<template>
	<InputTextBase
		ref="$input"
		v-model:focused="focused"
		class="TqInputString"
		:active="multi.subfocus"
		:modelValue="display"
		:theme="theme"
		:font="font"
		:align="align"
		:inline-position="inlinePosition"
		:block-position="blockPosition"
		:disabled="disabled"
		:invalid="invalid"
		:default="props.default"
		@focus="onFocus"
		@blur="onBlur"
		@input="onInput"
		@keydown="onKeyDown"
		@keydown.enter="confirm"
		@reset="onReset"
	/>
</template>
