// packages/react/src/components/ParameterGrid/ParameterHeading.tsx
import {type HTMLAttributes, type ReactNode} from 'react'

import {classNames} from '../../classNames'

export interface ParameterHeadingProps extends HTMLAttributes<HTMLLIElement> {
	right?: ReactNode
}

export function ParameterHeading({
	right,
	children,
	className,
	...props
}: ParameterHeadingProps) {
	return (
		<li
			{...props}
			className={classNames('TqParameterHeading', className)}
			data-tq-component="parameter-heading"
			data-tq-part="root"
		>
			<div data-tq-part="heading">{children}</div>
			<div data-tq-part="right">{right}</div>
		</li>
	)
}

// packages/vue/src/ParameterGrid/ParameterHeading.vue
<script setup lang="ts">
defineSlots<{
	default: void
	right: void
}>()
</script>
<template>
	<li class="TqParameterHeading" data-tq-component="parameter-heading" data-tq-part="root">
		<div class="heading" data-tq-part="heading">
			<slot />
		</div>
		<div class="right" data-tq-part="right">
			<slot name="right" />
		</div>
	</li>
</template>
