// src/react/components/ParameterGrid/ParameterGroup.tsx
import {type HTMLAttributes, type ReactNode, useMemo, useState} from 'react'

import {appConfigStore} from '../../../core'
import {classNames} from '../../classNames'
import {useConfigRef} from '../../hooks'
import {Icon} from '../Icon'
import styles from './ParameterGroup.module.styl'
import {ParameterHeading} from './ParameterHeading'

export interface ParameterGroupProps extends HTMLAttributes<HTMLDivElement> {
	name: string
	label: string
	icon?: string
	headingRight?: ReactNode
}

export function ParameterGroup({
	name,
	label,
	icon,
	headingRight,
	children,
	className,
	...props
}: ParameterGroupProps) {
	const entry = useMemo(() => appConfigStore.getState().ref(name, true), [name])
	const [expanded, setExpanded] = useConfigRef(entry)
	const [clipped, setClipped] = useState(!expanded)

	return (
		<div
			{...props}
			className={classNames(
				styles.group,
				!expanded && styles.collapsed,
				className
			)}
			onTransitionEnd={event => {
				if (event.propertyName === 'grid-template-rows') setClipped(!expanded)
			}}
		>
			<ParameterHeading right={expanded ? headingRight : undefined}>
				<button
					type="button"
					className={styles.heading}
					onClick={() => {
						if (expanded) setClipped(true)
						setExpanded(!expanded)
					}}
				>
					<Icon className={styles.chevron} icon="mdi:chevron-down" />
					{icon && <Icon className={styles.groupIcon} icon={icon} />}
					<span>{label}</span>
				</button>
			</ParameterHeading>
			<div className={classNames(styles.content, clipped && styles.clipped)}>
				{children}
			</div>
		</div>
	)
}

// packages/vue/src/ParameterGrid/ParameterGroup.vue
<script setup lang="ts">
import {ref, watch} from 'vue'

import {Icon} from '../Icon'
import {useAppConfigStore} from '../stores/appConfig'
import ParameterHeading from './ParameterHeading.vue'
import {ParameterGroupProps} from './types'

const props = defineProps<ParameterGroupProps>()

defineSlots<{
	default: void
	headingRight: void
}>()

const appConfig = useAppConfigStore()

const expanded = appConfig.ref(props.name, true)

// The 0fr↔1fr collapse needs overflow:hidden to clip the content, but that also
// crops focus outlines of inputs once the group is open. So clip only while
// collapsed or mid-animation: clip immediately on collapse, then unclip once the
// expand transition finishes.
const clipped = ref(!expanded.value)

watch(expanded, expanded => {
	if (!expanded) clipped.value = true
})

function onTransitionEnd(e: TransitionEvent) {
	if (e.propertyName === 'grid-template-rows') {
		clipped.value = !expanded.value
	}
}
</script>

<template>
	<div
		class="ParameterGroup"
		:class="{collapsed: !expanded}"
		data-tq-component="parameter-group"
		:data-tq-collapsed="!expanded ? '' : undefined"
		data-tq-part="root"
		@transitionend="onTransitionEnd">
		<ParameterHeading>
			<template #default>
				<button
					type="button"
					class="heading"
					:aria-expanded="expanded"
					data-tq-part="trigger"
					@click="expanded = !expanded"
				>
					<Icon
						class="chevron"
						data-tq-part="chevron"
						icon="mdi:chevron-down"
					/>
					<Icon
						v-if="icon"
						class="group-icon"
						data-tq-part="group-icon"
						:icon="icon"
					/>
					<span>{{ label }}</span>
				</button>
			</template>
			<template #right>
				<slot v-if="expanded" name="headingRight" />
			</template>
		</ParameterHeading>
		<!-- Always rendered; the 0fr↔1fr grid-row animates the height. -->
		<div
			class="content"
			:class="{clipped}"
			data-tq-part="content"
			:data-tq-clipped="clipped ? '' : undefined"
		>
			<slot />
		</div>
	</div>
</template>
