// packages/react/src/components/MultiSelectPopup/MultiSelectButton.tsx
import {useTweeqRuntime} from '../../runtime'
import {IconIndicator} from '../IconIndicator'

export function MultiSelectButton({
	icon,
	label,
	update,
}: {
	icon: string
	label: string
	update: (values: number[]) => number[]
}) {
	const {multiSelectStore} = useTweeqRuntime()
	const edit = () => {
		multiSelectStore.getState().updateValues(update)
		multiSelectStore.getState().confirmValues()
	}

	return (
		<IconIndicator
			aria-label={label}
			data-tq-multi-select-action="button"
			data-tq-part="button"
			icon={icon}
			onChangeActive={edit}
		/>
	)
}

// packages/vue/src/MultiSelectPopup/MultiSelectButton.vue
<script setup lang="ts">
import {IconIndicator} from '../IconIndicator'
import {useMultiSelectStore} from '../stores/multiSelect'

const props = defineProps<{
	icon: string
	label: string
	updator: (values: number[]) => number[]
}>()

const multiSelect = useMultiSelectStore()

function edit() {
	multiSelect.updateValues(props.updator)
	multiSelect.confirmValues()
}
</script>

<template>
	<IconIndicator
		class="TqMultiSelectButton"
		:icon="icon"
		:aria-label="label"
		data-tq-multi-select-action="button"
		data-tq-part="button"
		@update:active="edit"
	/>
</template>
