// src/react/components/Timeline/Timeline.tsx
import {scalar, type vec2} from 'linearly'
import {
	type CSSProperties,
	forwardRef,
	type HTMLAttributes,
	type ReactNode,
	useEffect,
	useImperativeHandle,
	useMemo,
	useRef,
	useState,
	type WheelEvent,
} from 'react'

import {
	clampTimelineRange,
	getTimelineScrollBounds,
	showTimelineRange,
	toPercent,
} from '../../../core'
import {classNames} from '../../classNames'
import {useElementBounding} from '../../hooks'
import styles from './Timeline.module.styl'

export interface TimelineRenderProps {
	range: vec2
	visibleFrameRange: vec2
	rangeStyle(range: vec2 | number): CSSProperties
	offsetStyle(offset: number): CSSProperties
}

export interface TimelineProps
	extends Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
	frameRange: vec2
	frameWidth?: number
	onChangeFrameWidth?: (value: number) => void
	frameWidthRange?: vec2
	overscroll?: number
	onConfirm?: () => void
	children?: (props: TimelineRenderProps) => ReactNode
	renderScrollbarRight?: () => ReactNode
}

export interface TimelineHandle {
	showRange(range: vec2 | number): void
	centerFrame(frame: number): void
}

export const Timeline = forwardRef<TimelineHandle, TimelineProps>(
	function TimelineComponent(
		{
			frameRange,
			frameWidth = 60,
			onChangeFrameWidth,
			frameWidthRange = [10, 100],
			overscroll = 0.5,
			onConfirm,
			children,
			renderScrollbarRight,
			className,
			...props
		},
		forwardedRef
	) {
		const fixed = useRef<HTMLDivElement>(null)
		const {width: containerWidth} = useElementBounding(fixed)
		const [range, setRange] = useState<vec2>(frameRange)
		const confirmTimer = useRef<ReturnType<typeof setTimeout> | undefined>(
			undefined
		)
		const stateRef = useRef({
			range,
			frameRange,
			frameWidth,
			frameWidthRange,
			overscroll,
		})
		stateRef.current = {
			range,
			frameRange,
			frameWidth,
			frameWidthRange,
			overscroll,
		}

		useEffect(() => {
			setRange(current => [
				current[0],
				current[0] + containerWidth / frameWidth,
			])
		}, [containerWidth, frameWidth])
		useEffect(() => () => clearTimeout(confirmTimer.current), [])

		useImperativeHandle(
			forwardedRef,
			() => ({
				showRange(shown) {
					setRange(current => showTimelineRange(current, shown))
				},
				centerFrame(frame) {
					setRange(current => {
						const duration = current[1] - current[0]
						return [frame - duration / 2, frame + duration / 2]
					})
				},
			}),
			[]
		)

		const visibleFrameRange: vec2 = [
			Math.max(Math.floor(range[0]), frameRange[0]),
			Math.min(Math.ceil(range[1]), frameRange[1]),
		]
		const toOffset = (frame: number) => (frame - range[0]) * frameWidth
		const rangeStyle = (shown: vec2 | number): CSSProperties => {
			const [start, end] =
				typeof shown === 'number' ? [shown, shown + 1] : shown
			return {
				transform: `translateX(${toOffset(start)}px)`,
				width: `${(end - start + 1) * frameWidth}px`,
			}
		}
		const offsetStyle = (offset: number): CSSProperties => ({
			transform: `translateX(${toOffset(offset)}px)`,
		})

		const barStyle = useMemo(() => {
			const duration = range[1] - range[0]
			const contentDuration = frameRange[1] - frameRange[0]
			const width = Math.min(duration / contentDuration, 1)
			const [minStart, maxStart] = getTimelineScrollBounds(
				frameRange,
				duration,
				overscroll
			)
			const center =
				minStart < maxStart ? scalar.invlerp(minStart, maxStart, range[0]) : 0.5
			return {width: toPercent(width), left: toPercent(center - width / 2)}
		}, [frameRange, overscroll, range])

		const onWheel = (event: WheelEvent<HTMLDivElement>) => {
			event.preventDefault()
			const current = stateRef.current
			if (event.altKey) {
				const zoom = 1.003 ** event.deltaY
				const nextWidth = Math.max(
					current.frameWidthRange[0],
					Math.min(current.frameWidthRange[1], current.frameWidth * zoom)
				)
				const appliedZoom = nextWidth / current.frameWidth
				const rect = fixed.current?.getBoundingClientRect()
				const x = rect ? event.clientX - rect.left : 0
				const origin = scalar.fit(
					x,
					0,
					containerWidth,
					current.range[0],
					current.range[1]
				)
				onChangeFrameWidth?.(nextWidth)
				clearTimeout(confirmTimer.current)
				confirmTimer.current = setTimeout(() => onConfirm?.(), 300)
				setRange(
					clampTimelineRange(
						[
							origin - (origin - current.range[0]) / appliedZoom,
							origin + (current.range[1] - origin) / appliedZoom,
						],
						current.frameRange,
						current.overscroll
					)
				)
			} else {
				const delta = (event.deltaX || event.deltaY) / current.frameWidth
				setRange(
					clampTimelineRange(
						[current.range[0] + delta, current.range[1] + delta],
						current.frameRange,
						current.overscroll
					)
				)
			}
		}

		return (
			<div {...props} className={classNames(styles.tqTimeline, className)}>
				<div className={styles.container}>
					<div ref={fixed} className={styles.fixed} onWheel={onWheel}>
						{children?.({range, visibleFrameRange, rangeStyle, offsetStyle})}
					</div>
				</div>
				<div className={styles.scrollbar}>
					<div className={styles.knob} style={barStyle} />
					{renderScrollbarRight?.()}
				</div>
			</div>
		)
	}
)

// packages/vue/src/Timeline/Timeline.vue
<script setup lang="ts">
import {
	centerTimelineFrame,
	getTimelineScrollBounds,
	panTimelineRange,
	showTimelineRange,
	toPercent,
	zoomTimelineRange,
} from '@tweeq/core'
import {useElementBounding} from '@vueuse/core'
import {scalar, type vec2} from 'linearly'
import {
	computed,
	onBeforeUnmount,
	shallowRef,
	useTemplateRef,
	watch,
} from 'vue'

import type {TimelineProps} from './types'

const props = withDefaults(defineProps<TimelineProps>(), {
	frameWidth: 60,
	frameWidthRange: () => [10, 100],
	overscroll: 0.5,
})

defineSlots<{
	default(props: {
		range: vec2
		visibleFrameRange: vec2
		rangeStyle: (range: vec2 | number) => any
		offsetStyle: (offset: number) => any
	}): void
	scrollbarRight: void
}>()

const range = shallowRef<vec2>(props.frameRange ?? [0, 1])

const visibleFrameRange = computed<vec2>(() => {
	const [startFrame, endFrame] = props.frameRange
	const [start, end] = range.value
	return [
		Math.max(Math.floor(start), startFrame),
		Math.min(Math.ceil(end), endFrame),
	]
})

const emit = defineEmits<{
	'update:frameWidth': [number]
	/**
	 * Fired once the continuous frameWidth (zoom) change settles. Wheel-zoom has
	 * no natural pointer-up, so this is debounced. Consumers use it to close out a
	 * transaction opened on the first `update:frameWidth` (e.g. resuming autosave
	 * that was batched during the gesture).
	 */
	confirm: []
}>()

let confirmTimer: ReturnType<typeof setTimeout> | undefined
function scheduleConfirm() {
	clearTimeout(confirmTimer)
	confirmTimer = setTimeout(() => emit('confirm'), 300)
}
onBeforeUnmount(() => clearTimeout(confirmTimer))

const $root = useTemplateRef('$root')
const {width: containerWidth} = useElementBounding($root)

function onWheel(event: WheelEvent) {
	if (event.altKey) {
		const zoom = 1.003 ** event.deltaY
		const newFrameWidth = scalar.clamp(
			props.frameWidth * zoom,
			...props.frameWidthRange
		)
		const appliedZoom = newFrameWidth / props.frameWidth
		const rect = $root.value?.getBoundingClientRect()
		const x = rect ? event.clientX - rect.left : 0
		const origin = scalar.fit(
			x,
			0,
			containerWidth.value,
			range.value[0],
			range.value[1]
		)

		emit('update:frameWidth', newFrameWidth)
		scheduleConfirm()
		range.value = zoomTimelineRange(
			range.value,
			origin,
			appliedZoom,
			props.frameRange,
			props.overscroll
		)
	} else {
		range.value = panTimelineRange(
			range.value,
			event.deltaX || event.deltaY,
			props.frameWidth,
			props.frameRange,
			props.overscroll
		)
	}
}

const barStyles = computed(() => {
	const [start, end] = range.value
	const duration = end - start
	const [contentStart, contentEnd] = props.frameRange

	// Knob width = the visible fraction of the content (capped to the track).
	const width = Math.min(duration / (contentEnd - contentStart), 1)

	// The knob's CENTER tracks the scroll position across the full scrollable
	// travel: it sits at the track's left edge at the leftmost scroll and the
	// right edge at the rightmost, so the knob never runs off the track (only
	// its overhanging half is clipped at the extremes).
	const [minStart, maxStart] = getTimelineScrollBounds(
		props.frameRange,
		duration,
		props.overscroll
	)
	const center =
		minStart < maxStart ? scalar.invlerp(minStart, maxStart, start) : 0.5

	return {
		width: toPercent(width),
		left: toPercent(center - width / 2),
	}
})

watch(
	() => [containerWidth.value, props.frameWidth] as const,
	([w, ppu]) => {
		const [start] = range.value

		range.value = [start, start + w / ppu]
	}
)

function showRange(showRange: vec2 | number) {
	range.value = showTimelineRange(range.value, showRange)
}

/**
 * Scrolls so that the given frame sits at the horizontal center of the view,
 * keeping the current zoom (visible duration).
 */
function centerFrame(frame: number) {
	range.value = centerTimelineFrame(range.value, frame)
}

defineExpose({
	showRange,
	centerFrame,
})

function toOffset(frame: number) {
	return (frame - range.value[0]) * props.frameWidth
}

function rangeStyle(range: number | vec2) {
	const [start, end] = typeof range === 'number' ? [range, range + 1] : range

	const x = toOffset(start)
	const width = (end - start + 1) * props.frameWidth

	return {
		transform: `translateX(${x}px)`,
		width: `${width}px`,
	}
}

function offsetStyle(offset: number) {
	const x = toOffset(offset)

	return {
		transform: `translateX(${x}px)`,
	}
}
</script>

<template>
	<div class="TqTimeline" data-tq-component="timeline" data-tq-part="root">
		<div class="container" data-tq-part="container">
			<div
				ref="$root"
				class="fixed"
				data-tq-part="fixed"
				@wheel.prevent="onWheel"
			>
				<slot
					:range="range"
					:visibleFrameRange="visibleFrameRange"
					:rangeStyle="rangeStyle"
					:offsetStyle="offsetStyle"
				/>
			</div>
		</div>
		<div ref="$scrollbar" class="scrollbar" data-tq-part="scrollbar">
			<div ref="$knob" class="knob" :style="barStyles" data-tq-part="knob" />
			<slot name="scrollbarRight" />
		</div>
	</div>
</template>
