// packages/react/src/components/InputColor/InputColorPresets.tsx
import {type HTMLAttributes} from 'react'

import {useInputColorContext} from './InputColorContext'

export interface InputColorPresetsProps
	extends Omit<HTMLAttributes<HTMLDivElement>, 'onChange'> {
	presets?: readonly string[]
	onChange?: (value: string) => void
	disabled?: boolean
}

export function InputColorPresets({
	presets = [],
	onChange,
	disabled,
	className,
	...props
}: InputColorPresetsProps) {
	const {presets: inherited} = useInputColorContext()
	const merged = [...inherited, ...presets]

	return (
		<div
			{...props}
			className={className}
			data-tq-component="input-color-presets"
			data-tq-part="presets"
		>
			{merged.map((preset, index) => (
				<button
					type="button"
					key={`${preset}-${index}`}
					disabled={disabled}
					aria-label={`Use ${preset}`}
					data-tq-part={`preset-${index}`}
					style={{background: preset}}
					onClick={() => onChange?.(preset)}
				/>
			))}
		</div>
	)
}

// packages/vue/src/InputColor/InputColorPresets.vue
<script setup lang="ts">
import {computed, inject} from 'vue'

import {DefaultColorPresets, InputColorPresetsKey} from './useInputColor'

interface Props {
	presets?: string[]
	disabled?: boolean
}

const props = withDefaults(defineProps<Props>(), {
	presets: () => [],
})

const emit = defineEmits<{
	'update:modelValue': [string]
}>()

const injectedPresets = inject(InputColorPresetsKey, DefaultColorPresets)
const presetsMerged = computed(() => [...injectedPresets, ...props.presets])
</script>

<template>
	<div
		class="TqInputColorPresets"
		data-tq-component="input-color-presets"
		data-tq-part="presets"
	>
		<button
			v-for="(preset, index) in presetsMerged"
			:key="`${preset}-${index}`"
			type="button"
			:disabled="props.disabled"
			:aria-label="`Use ${preset}`"
			:data-tq-part="`preset-${index}`"
			:style="{background: preset}"
			@click="emit('update:modelValue', preset)"
		/>
	</div>
</template>
./useInputColor
