// packages/vue/src/InputColor/InputColorPicker.vue
<script lang="ts" setup>
import {
	createInputColorPickerController,
	type HSVA,
} from '@tweeq/core'
import {shallowRef, watch} from 'vue'

import {Icon} from '../Icon'
import {InputEmits} from '../types'
import InputColorChannelPad from './InputColorChannelPad.vue'
import InputColorChannelSlider from './InputColorChannelSlider.vue'
import InputColorChannelValues from './InputColorChannelValues.vue'
import InputColorPresets from './InputColorPresets.vue'
import {DefaultColorPickers, type InputColorProps} from './types'

const props = withDefaults(defineProps<InputColorProps>(), {
	alpha: true,
	pickers: () => DefaultColorPickers,
})

const emit = defineEmits<InputEmits>()

const model = defineModel<string>({required: true})

const local = shallowRef<HSVA>({h: 0, s: 0, v: 0, a: 1})
const controller = createInputColorPickerController(model.value, {
	onChange(value) {
		model.value = value
	},
	onUpdate(value) {
		local.value = value
	},
})
local.value = controller.value

watch(
	model,
	model => controller.sync(model),
	{flush: 'sync'}
)

// EyeDropper
const isEyeDropperSupported =
	typeof window !== 'undefined' && 'EyeDropper' in window

async function pickColor() {
	const eyeDropper = new (window as any)['EyeDropper']()
	try {
		controller.updateCode((await eyeDropper.open()).sRGBHex)
		emit('confirm')
	} catch (error) {
		if (error instanceof DOMException && error.name === 'AbortError') return
		throw error
	}
}
</script>

<template>
	<div
		class="TqInputColorPicker"
		data-tq-component="input-color-picker"
		data-tq-part="picker"
	>
		<template v-for="([type, ch], i) in pickers">
			<InputColorChannelPad
				v-if="type === 'pad'"
				:key="i"
				:modelValue="local"
				:axes="ch"
				:disabled="props.disabled"
				@update:modelValue="controller.updateHSVA"
			/>
			<InputColorChannelSlider
				v-if="type === 'slider' && !(!alpha && ch === 'a')"
				:key="i"
				:modelValue="local"
				:axis="ch"
				:disabled="props.disabled"
				@update:modelValue="controller.updateHSVA"
			/>
			<InputColorChannelValues
				v-if="type === 'values'"
				:key="i"
				:colorCode="modelValue"
				:hsva="local"
				:alpha="alpha"
				:disabled="props.disabled"
				@update:colorCode="controller.updateCode"
				@update:hsva="controller.updateHSVA"
			/>
		</template>
		<InputColorPresets
			:presets="presets"
			:disabled="props.disabled"
			@update:modelValue="controller.updateCode($event); emit('confirm')"
		/>
		<button
			v-if="isEyeDropperSupported"
			type="button"
			class="eyeDropper"
			:disabled="props.disabled"
			aria-label="Pick a color from the screen"
			data-tq-part="eye-dropper"
			@click="pickColor"
		>
			<Icon icon="material-symbols:colorize" />
		</button>
	</div>
</template>

// src/react/components/InputColor/InputColorPicker.tsx
import {type HTMLAttributes, useEffect, useRef, useState} from 'react'

import {
	type ColorPickerComponent,
	css2hsva,
	DEFAULT_COLOR_PICKERS,
	type HSVA,
	hsva2hex,
} from '../../../core'
import {classNames} from '../../classNames'
import {Icon} from '../Icon'
import {InputColorChannelPad} from './InputColorChannelPad'
import {InputColorChannelSlider} from './InputColorChannelSlider'
import {InputColorChannelValues} from './InputColorChannelValues'
import styles from './InputColorPicker.module.styl'
import {InputColorPresets} from './InputColorPresets'

interface EyeDropperResult {
	sRGBHex: string
}

interface EyeDropperConstructor {
	new (): {open(): Promise<EyeDropperResult>}
}

export interface InputColorPickerProps
	extends Omit<HTMLAttributes<HTMLDivElement>, 'onChange'> {
	value: string
	onChange?: (value: string) => void
	onConfirm?: () => void
	alpha?: boolean
	pickers?: readonly ColorPickerComponent[]
	presets?: readonly string[]
}

export function InputColorPicker({
	value,
	onChange,
	onConfirm,
	alpha = true,
	pickers = DEFAULT_COLOR_PICKERS,
	presets,
	className,
	...props
}: InputColorPickerProps) {
	const [local, setLocal] = useState<HSVA>(() => css2hsva(value))
	const emitted = useRef<string | null>(null)

	useEffect(() => {
		if (value !== emitted.current) setLocal(css2hsva(value))
	}, [value])

	const updateLocal = (next: HSVA) => {
		setLocal(next)
		emitted.current = hsva2hex(next)
		onChange?.(emitted.current)
	}
	const updateCode = (next: string) => {
		setLocal(css2hsva(next))
		emitted.current = next
		onChange?.(next)
	}
	const EyeDropper =
		typeof window === 'undefined'
			? undefined
			: (window as unknown as {EyeDropper?: EyeDropperConstructor}).EyeDropper

	return (
		<div {...props} className={classNames(styles.picker, className)}>
			{pickers.map((picker, index) => {
				if (picker[0] === 'pad') {
					return (
						<InputColorChannelPad
							key={index}
							value={local}
							axes={picker[1]}
							onChange={updateLocal}
						/>
					)
				}
				if (picker[0] === 'slider') {
					if (!alpha && picker[1] === 'a') return null
					return (
						<InputColorChannelSlider
							key={index}
							value={local}
							axis={picker[1]}
							onChange={updateLocal}
						/>
					)
				}
				if (picker[0] === 'values') {
					return (
						<InputColorChannelValues
							key={index}
							colorCode={value}
							value={local}
							alpha={alpha}
							onChange={updateLocal}
							onChangeColorCode={updateCode}
						/>
					)
				}
				return null
			})}
			<InputColorPresets
				presets={presets}
				onChange={next => {
					updateCode(next)
					onConfirm?.()
				}}
			/>
			{EyeDropper && (
				<button
					type="button"
					className={styles.eyeDropper}
					aria-label="Pick a color from the screen"
					onClick={async () => {
						const result = await new EyeDropper().open()
						updateCode(result.sRGBHex)
						onConfirm?.()
					}}
				>
					<Icon icon="material-symbols:colorize" />
				</button>
			)}
		</div>
	)
}
