// packages/react/src/components/Tabs/Tab.tsx
import {normalizeTabId} from '@tweeq/core'
import {type HTMLAttributes, useContext, useEffect, useMemo} from 'react'

import {classNames} from '../../classNames'
import {TabsContext} from './TabsContext'

export interface TabProps extends HTMLAttributes<HTMLElement> {
	id?: string
	name: string
	isDisabled?: boolean
}

export function Tab({
	id: idProp,
	name,
	isDisabled = false,
	className,
	children,
	...props
}: TabProps) {
	const context = useContext(TabsContext)
	if (!context) throw new Error('Tab must be rendered inside Tabs')
	const {activeId, register, update} = context
	const id = idProp ?? normalizeTabId(name)
	const registration = useMemo(
		() => ({id, name, isDisabled, paneId: `${id}-pane`}),
		[id, isDisabled, name]
	)
	useEffect(() => register(registration), [register, registration])
	useEffect(() => update(registration), [registration, update])
	const active = activeId === id

	return (
		<section
			{...props}
			id={registration.paneId}
			className={classNames('TqTab', active && 'active', className)}
			data-tab-id={id}
			data-tq-active={active ? '' : undefined}
			data-tq-component="tab"
			data-tq-part={`panel-${id}`}
			aria-hidden={!active}
			role="tabpanel"
			tabIndex={-1}
		>
			{children}
		</section>
	)
}

// packages/vue/src/Tabs/Tab.vue
<script setup lang="ts">
import {normalizeTabId} from '@tweeq/core'
import {computed, onBeforeMount, onBeforeUnmount, watch} from 'vue'

import {AddTabKey, DeleteTabKey, TabsProviderKey, UpdateTabKey} from './symbols'
import {injectStrict} from './utils'

type Props = {
	id?: string
	name: string
	isDisabled?: boolean
}

const props = withDefaults(defineProps<Props>(), {
	id: undefined,
	isDisabled: false,
})

const tabsProvider = injectStrict(TabsProviderKey)
const addTab = injectStrict(AddTabKey)
const updateTab = injectStrict(UpdateTabKey)
const deleteTab = injectStrict(DeleteTabKey)

const id = computed(() =>
	props.id ? props.id : normalizeTabId(props.name)
)
const paneId = computed(() => id.value + '-pane')
const isActive = computed(() => id.value === tabsProvider.activeId)

const descriptor = () => ({
	name: props.name,
	isDisabled: props.isDisabled,
	id: id.value,
	paneId: paneId.value,
})

watch([id, () => props.name, () => props.isDisabled], ([nextId], [oldId]) => {
	if (oldId && oldId !== nextId) {
		deleteTab(oldId)
		addTab(descriptor())
	} else {
		updateTab(nextId, {
			name: props.name,
			isDisabled: props.isDisabled,
			id: nextId,
			paneId: paneId.value,
		})
	}
})

onBeforeMount(() => addTab(descriptor()))

onBeforeUnmount(() => {
	deleteTab(id.value)
})
</script>

<template>
	<section
		:id="paneId"
		ref="tab"
		class="TqTab"
		:class="{active: isActive}"
		:data-tab-id="id"
		:data-tq-active="isActive ? '' : undefined"
		data-tq-component="tab"
		:data-tq-part="`panel-${id}`"
		:aria-hidden="!isActive"
		role="tabpanel"
		tabindex="-1"
	>
		<slot />
	</section>
</template>
